-- ============================================================
-- V20__create_patients.sql
-- Core patient demographics. One row per patient.
-- UHID is generated by the service layer using hospital_profile
-- format settings (uhid_prefix, separator, padding, year flag).
-- Schema ref: docs/03-schema/v3/modules/07-patient.html#patients
-- ============================================================

CREATE TABLE patients (

    id              uuid        NOT NULL DEFAULT uuidv7(),

    -- ── Identity ──────────────────────────────────────────────
    uhid            text        NOT NULL,
    first_name      text        NOT NULL,
    last_name       text        NOT NULL,
    date_of_birth   date        NOT NULL,
    gender          text        NOT NULL,
    blood_group     text,
    mobile          text,
    alt_mobile      text,
    email           text,

    -- ── Address (jsonb) + generated promotion columns ─────────
    address         jsonb,
    address_city    text GENERATED ALWAYS AS ((address->>'city'))    STORED,
    address_pincode text GENERATED ALWAYS AS ((address->>'pincode')) STORED,

    -- ── Emergency contact ─────────────────────────────────────
    emergency_contact_name      text,
    emergency_contact_mobile    text,
    emergency_contact_relation  text,

    -- ── Registration metadata ─────────────────────────────────
    created_via     text        NOT NULL DEFAULT 'web',
    is_deceased     boolean     NOT NULL DEFAULT false,
    deceased_at     date,

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by      uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    version         int         NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    deleted_by      uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_patients
        PRIMARY KEY (id),

    CONSTRAINT uq_patients_uhid
        UNIQUE (uhid),

    CONSTRAINT chk_patients_first_name_len
        CHECK (char_length(first_name) BETWEEN 1 AND 60),

    CONSTRAINT chk_patients_last_name_len
        CHECK (char_length(last_name) BETWEEN 1 AND 60),

    CONSTRAINT chk_patients_dob
        CHECK (date_of_birth <= current_date),

    CONSTRAINT chk_patients_gender
        CHECK (gender IN ('m','f','o')),

    CONSTRAINT chk_patients_blood_group
        CHECK (blood_group IS NULL OR blood_group IN ('A+','A-','B+','B-','AB+','AB-','O+','O-','unknown')),

    CONSTRAINT chk_patients_mobile_len
        CHECK (mobile IS NULL OR char_length(mobile) BETWEEN 10 AND 15),

    CONSTRAINT chk_patients_emergency_mobile_len
        CHECK (emergency_contact_mobile IS NULL OR char_length(emergency_contact_mobile) BETWEEN 10 AND 15),

    CONSTRAINT chk_patients_created_via
        CHECK (created_via IN ('web','android','ios','api','migration')),

    CONSTRAINT chk_patients_deceased
        CHECK (deceased_at IS NULL OR (is_deceased = true AND deceased_at <= current_date))
);

-- ── Indexes ───────────────────────────────────────────────────

-- Reception search by UHID
CREATE INDEX ix_patients_uhid
    ON patients (uhid)
    WHERE deleted_at IS NULL;

-- Search by phone number
CREATE INDEX ix_patients_mobile
    ON patients (mobile)
    WHERE mobile IS NOT NULL AND deleted_at IS NULL;

-- Prefix search by first/last name
CREATE INDEX ix_patients_first_name
    ON patients (first_name text_pattern_ops)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_patients_last_name
    ON patients (last_name text_pattern_ops)
    WHERE deleted_at IS NULL;

-- Area-based reports via generated column
CREATE INDEX ix_patients_city
    ON patients (address_city)
    WHERE address_city IS NOT NULL AND deleted_at IS NULL;

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_patients_bu_touch
    BEFORE UPDATE ON patients
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_patients_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON patients
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  patients IS 'One row per patient. UHID generated at registration using hospital_profile format. Allergies and chronic conditions live in child tables, not arrays.';
COMMENT ON COLUMN patients.uhid                         IS 'Unique Hospital ID (e.g. KH-2026-00042). Generated by service layer from hospital_profile UHID format columns.';
COMMENT ON COLUMN patients.first_name                   IS 'Patient first name as on government ID. 1–60 chars.';
COMMENT ON COLUMN patients.last_name                    IS 'Patient last name / family name as on government ID. 1–60 chars.';
COMMENT ON COLUMN patients.date_of_birth                IS 'Used to compute age at visit time — age is not stored separately.';
COMMENT ON COLUMN patients.gender                       IS 'm | f | o';
COMMENT ON COLUMN patients.blood_group                  IS 'A+ | A- | B+ | B- | AB+ | AB- | O+ | O- | unknown. NULL when not collected.';
COMMENT ON COLUMN patients.mobile                       IS 'Primary contact number. 10–15 chars when present.';
COMMENT ON COLUMN patients.alt_mobile                   IS 'Alternate contact number. 10–15 chars when present.';
COMMENT ON COLUMN patients.address                      IS 'Structured address jsonb: {line1, line2, city, state, pincode, country, landmark}.';
COMMENT ON COLUMN patients.address_city                 IS 'GENERATED from address->>''city''. Indexed for city-filter queries.';
COMMENT ON COLUMN patients.address_pincode              IS 'GENERATED from address->>''pincode''. Indexed for area-based reports.';
COMMENT ON COLUMN patients.emergency_contact_mobile     IS 'Emergency contact phone. 10–15 digits when present.';
COMMENT ON COLUMN patients.created_via                  IS 'web | android | ios | api | migration — channel that created the record.';
COMMENT ON COLUMN patients.is_deceased                  IS 'Suppresses appointment and prescription workflows when true.';
COMMENT ON COLUMN patients.deceased_at                  IS 'Date of death. Must be NULL when is_deceased = false.';
COMMENT ON COLUMN patients.version                      IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN patients.deleted_at                   IS 'Soft-delete timestamp. NULL = live row.';
