-- ============================================================
-- V28__create_appointments.sql
-- Patient-doctor appointment bookings. One row per booking.
-- appointment_no is generated by the service layer
-- (e.g. APT-2026-00001). Slot linkage is optional — walk-in
-- and emergency appointments may have no pre-existing slot.
-- ============================================================

CREATE TABLE appointments (

    id              uuid        NOT NULL DEFAULT uuidv7(),

    -- Human-readable booking reference — generated by service layer
    appointment_no  text        NOT NULL,

    patient_id      uuid        NOT NULL,
    doctor_id       uuid        NOT NULL,

    -- Optional: walk-in / emergency appointments have no slot
    slot_id         uuid,

    scheduled_at    timestamptz NOT NULL,
    visit_type      text        NOT NULL DEFAULT 'new',
    status          text        NOT NULL DEFAULT 'booked',
    source          text        NOT NULL,
    reason          text,

    -- Cancellation metadata — populated atomically with status = 'cancelled'
    cancelled_at    timestamptz,
    cancelled_by    uuid,
    cancel_reason   text,

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by      uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    version         int         NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    deleted_by      uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_appointments
        PRIMARY KEY (id),

    CONSTRAINT uq_appointments_no
        UNIQUE (appointment_no),

    CONSTRAINT chk_appointments_visit_type
        CHECK (visit_type IN ('new','follow_up','emergency','procedure')),

    CONSTRAINT chk_appointments_status
        CHECK (status IN ('booked','confirmed','arrived','in_consultation','completed','cancelled','no_show')),

    CONSTRAINT chk_appointments_source
        CHECK (source IN ('walk_in','phone','online','referral')),

    -- cancelled_at must be set if and only if status = 'cancelled'
    CONSTRAINT chk_appointments_cancellation
        CHECK ((status = 'cancelled' AND cancelled_at IS NOT NULL) OR (status != 'cancelled' AND cancelled_at IS NULL)),

    CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT,

    CONSTRAINT fk_appointments_doctor
        FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT fk_appointments_slot
        FOREIGN KEY (slot_id) REFERENCES appointment_slots(id) ON DELETE RESTRICT,

    CONSTRAINT fk_appointments_cancelled_by
        FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL
);

-- ── Indexes ───────────────────────────────────────────────────

-- Prevents double-booking a slot — partial so cancelled/no_show slots are re-bookable
CREATE UNIQUE INDEX uq_appointments_slot
    ON appointments (slot_id)
    WHERE slot_id IS NOT NULL AND status NOT IN ('cancelled','no_show');

-- Patient appointment history (upcoming and past)
CREATE INDEX ix_appointments_patient
    ON appointments (patient_id, scheduled_at DESC)
    WHERE deleted_at IS NULL;

-- Doctor schedule view
CREATE INDEX ix_appointments_doctor
    ON appointments (doctor_id, scheduled_at DESC)
    WHERE deleted_at IS NULL;

-- Ops dashboard — filter by status and date
CREATE INDEX ix_appointments_status
    ON appointments (status, scheduled_at)
    WHERE deleted_at IS NULL;

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_appointments_bu_touch
    BEFORE UPDATE ON appointments
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_appointments_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON appointments
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  appointments IS 'One row per patient-doctor booking. appointment_no generated by service layer (e.g. APT-2026-00001). Slot linkage optional — walk-in and emergency appointments have no pre-existing slot.';
COMMENT ON COLUMN appointments.appointment_no IS 'Human-readable booking reference (e.g. APT-2026-00001). Globally unique. Generated by service layer.';
COMMENT ON COLUMN appointments.slot_id        IS 'Links to appointment_slots when the booking was made against a pre-generated slot. NULL for walk-in and emergency visits.';
COMMENT ON COLUMN appointments.visit_type     IS 'new | follow_up | emergency | procedure.';
COMMENT ON COLUMN appointments.status         IS 'booked → confirmed → arrived → in_consultation → completed. Alternate terminal states: cancelled | no_show.';
COMMENT ON COLUMN appointments.source         IS 'walk_in | phone | online | referral — how the appointment was created.';
COMMENT ON COLUMN appointments.cancelled_at   IS 'Timestamp when status transitioned to cancelled. Must be non-NULL iff status = cancelled.';
COMMENT ON COLUMN appointments.cancelled_by   IS 'User who cancelled. NULL if patient self-cancelled via app (no staff account).';
COMMENT ON COLUMN appointments.cancel_reason  IS 'Free-text reason for cancellation.';
COMMENT ON COLUMN appointments.version        IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN appointments.deleted_at     IS 'Soft-delete timestamp. NULL = live row.';
