-- ============================================================
-- V29__create_op_visits.sql
-- Outpatient visit record. One row per visit (walk-in or booked).
-- op_number generated by the service layer (e.g. OP-2026-00101).
-- current_state_code is deferred — patient_states table added later.
-- Also wires the deferred FK from patient_journey_events.op_visit_id.
-- ============================================================

CREATE TABLE op_visits (

    id              uuid        NOT NULL DEFAULT uuidv7(),

    -- Human-readable visit reference — generated by service layer
    op_number       text        NOT NULL,

    patient_id      uuid        NOT NULL,

    -- Optional: walk-in visits have no prior appointment
    appointment_id  uuid,

    doctor_id       uuid        NOT NULL,
    visit_date      date        NOT NULL,
    chief_complaint text,

    -- Populated when the visit is administratively closed
    closed_at       timestamptz,

    -- Emergency & MLC metadata
    is_emergency    boolean     NOT NULL DEFAULT false,
    emergency_triage text,
    is_mlc          boolean     NOT NULL DEFAULT false,
    mlc_number      text,

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by      uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    version         int         NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    deleted_by      uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_op_visits
        PRIMARY KEY (id),

    CONSTRAINT uq_op_visits_number
        UNIQUE (op_number),

    CONSTRAINT chk_op_visits_triage
        CHECK (emergency_triage IS NULL OR emergency_triage IN ('red','yellow','green')),

    -- Triage level only meaningful for emergency visits
    CONSTRAINT chk_op_visits_emergency_consistency
        CHECK (is_emergency = true OR emergency_triage IS NULL),

    -- MLC number only meaningful when MLC flag is set
    CONSTRAINT chk_op_visits_mlc_consistency
        CHECK (is_mlc = true OR mlc_number IS NULL),

    CONSTRAINT fk_op_visits_patient
        FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT,

    CONSTRAINT fk_op_visits_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE RESTRICT,

    CONSTRAINT fk_op_visits_doctor
        FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE RESTRICT
);

-- ── Indexes ───────────────────────────────────────────────────

-- Patient visit history
CREATE INDEX ix_op_visits_patient
    ON op_visits (patient_id, visit_date DESC)
    WHERE deleted_at IS NULL;

-- Doctor workload by date
CREATE INDEX ix_op_visits_doctor
    ON op_visits (doctor_id, visit_date)
    WHERE deleted_at IS NULL;

-- Ops / daily census view
CREATE INDEX ix_op_visits_date
    ON op_visits (visit_date)
    WHERE deleted_at IS NULL;

-- Emergency triage queue
CREATE INDEX ix_op_visits_emergency
    ON op_visits (visit_date)
    WHERE is_emergency = true AND deleted_at IS NULL;

-- Appointment → OP visit lookup (is appointment paid? / get OP for appointment)
CREATE INDEX ix_op_visits_appointment
    ON op_visits (appointment_id)
    WHERE appointment_id IS NOT NULL AND deleted_at IS NULL;

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_op_visits_bu_touch
    BEFORE UPDATE ON op_visits
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_op_visits_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON op_visits
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  op_visits IS 'One row per outpatient visit (walk-in or booked). op_number generated by service layer (e.g. OP-2026-00101). current_state_code column deferred until patient_states table is created.';
COMMENT ON COLUMN op_visits.op_number        IS 'Human-readable visit reference (e.g. OP-2026-00101). Globally unique. Generated by service layer.';
COMMENT ON COLUMN op_visits.appointment_id   IS 'Links to the prior appointment if the patient booked in advance. NULL for walk-in and emergency visits.';
COMMENT ON COLUMN op_visits.chief_complaint  IS 'Patient-reported presenting complaint captured at registration. Free text.';
COMMENT ON COLUMN op_visits.closed_at        IS 'Timestamp when the visit was administratively closed (billing settled, patient discharged). NULL = open visit.';
COMMENT ON COLUMN op_visits.is_emergency     IS 'TRUE flags the visit for emergency queue and triage workflow.';
COMMENT ON COLUMN op_visits.emergency_triage IS 'red | yellow | green triage severity. NULL unless is_emergency = true.';
COMMENT ON COLUMN op_visits.is_mlc           IS 'Medico-Legal Case flag. Enables MLC documentation workflow.';
COMMENT ON COLUMN op_visits.mlc_number       IS 'Police or MLC reference number. NULL unless is_mlc = true.';
COMMENT ON COLUMN op_visits.version          IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN op_visits.deleted_at       IS 'Soft-delete timestamp. NULL = live row.';

-- ── Deferred FK from patient_journey_events ───────────────────
-- op_visits did not exist when patient_journey_events was created (V26).
-- Now that op_visits is in place, the FK can be wired.

ALTER TABLE patient_journey_events
    ADD CONSTRAINT fk_patient_journey_events_visit
    FOREIGN KEY (op_visit_id) REFERENCES op_visits(id) ON DELETE RESTRICT;
