-- ============================================================
-- V2__create_users.sql
-- users table — every staff account (auth + HR) in one row.
-- Schema ref: docs/03-schema/v3/modules/01a-identity-and-auth.html#users
-- ============================================================

CREATE TABLE users (

    -- Primary key — UUIDv7 generated client-side by Hibernate.
    -- uuidv7() fallback is used only for direct SQL inserts / seed data.
    id                      uuid        NOT NULL DEFAULT uuidv7(),

    -- ── HR identity ──────────────────────────────────────────
    employee_id             text        NOT NULL,
    full_name               text        NOT NULL,
    department_id           uuid,                       -- FK → departments(id) added in V_departments
    designation             text,
    joining_date            date,
    profile_data            jsonb       NOT NULL DEFAULT '{}',

    -- ── Auth — login identifiers ─────────────────────────────
    username                text        NOT NULL,
    mobile                  text        NOT NULL,
    email                   text,

    -- ── Auth — credentials & security state ──────────────────
    password_hash           text        NOT NULL,
    password_changed_at     timestamptz NOT NULL DEFAULT now(),
    must_change_password    boolean     NOT NULL DEFAULT FALSE,
    failed_attempts         int         NOT NULL DEFAULT 0,
    locked_until            timestamptz,
    mfa_enabled             boolean     NOT NULL DEFAULT FALSE,
    mfa_secret              text,
    status                  text        NOT NULL DEFAULT 'active',
    token_version           int         NOT NULL DEFAULT 0,

    -- ── Telemetry ─────────────────────────────────────────────
    last_login_at           timestamptz,
    last_login_ip           text,
    last_login_user_agent   text,
    notes                   text,

    -- ── Uniform audit + soft-delete block (every v3 table) ───
    created_by              uuid        NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_by              uuid,
    updated_at              timestamptz NOT NULL DEFAULT now(),
    version                 int         NOT NULL DEFAULT 0,  -- owned by Hibernate @Version
    deleted_at              timestamptz,
    deleted_by              uuid,

    -- ── Table constraints ─────────────────────────────────────
    CONSTRAINT pk_users
        PRIMARY KEY (id),

    CONSTRAINT chk_users_status
        CHECK (status IN ('active', 'inactive', 'suspended')),

    CONSTRAINT chk_users_username_len
        CHECK (char_length(username) BETWEEN 3 AND 64),

    CONSTRAINT chk_users_mobile_len
        CHECK (char_length(mobile) BETWEEN 10 AND 15),

    CONSTRAINT chk_users_failed_attempts
        CHECK (failed_attempts >= 0)
);

-- ── Indexes ───────────────────────────────────────────────────

-- Unique identifiers — partial so a re-registered user (new row) is allowed
CREATE UNIQUE INDEX uq_users_employee_id
    ON users (employee_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_users_username
    ON users (username)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_users_mobile
    ON users (mobile)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_users_email
    ON users (email)
    WHERE email IS NOT NULL AND deleted_at IS NULL;

-- Lookup indexes
CREATE INDEX ix_users_status
    ON users (status)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_users_department
    ON users (department_id)
    WHERE department_id IS NOT NULL AND deleted_at IS NULL;

-- Trigram index for full-name search (reception staff lookup)
CREATE INDEX ix_users_full_name_trgm
    ON users USING gin (full_name gin_trgm_ops);

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE (version is Hibernate's responsibility)
CREATE TRIGGER tr_users_bu_touch
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  users IS 'Every staff account — admin, doctors, nurses, receptionists, pharmacists, lab/radio techs — in one row each. Auth and HR live together.';
COMMENT ON COLUMN users.id                    IS 'Surrogate primary key — UUIDv7 generated by Hibernate client-side.';
COMMENT ON COLUMN users.employee_id           IS 'HR / payroll identifier (e.g. EMP010). Unique per live row.';
COMMENT ON COLUMN users.full_name             IS 'Display name used on rosters and prescriptions.';
COMMENT ON COLUMN users.department_id         IS 'Primary department. NULL for cross-cutting roles. FK wired in department migration.';
COMMENT ON COLUMN users.profile_data          IS 'Role-specific jsonb extension keyed by type discriminator: admin | doctor | receptionist | pharmacist | lab_tech.';
COMMENT ON COLUMN users.username              IS 'Primary login handle. Unique per live row.';
COMMENT ON COLUMN users.mobile                IS 'Login alternate and contact number. Unique per live row.';
COMMENT ON COLUMN users.email                 IS 'Login alternate and password-reset target. Partial unique (non-null live rows).';
COMMENT ON COLUMN users.password_hash         IS 'BCrypt hash (cost 12).';
COMMENT ON COLUMN users.must_change_password  IS 'TRUE forces a password-change flow on next login. Set on provisioning and admin reset.';
COMMENT ON COLUMN users.failed_attempts       IS 'Consecutive failed login counter. Reset to 0 on success.';
COMMENT ON COLUMN users.locked_until          IS 'Lockout window end. NULL = not locked.';
COMMENT ON COLUMN users.mfa_secret            IS 'TOTP seed — encrypted at application layer before storage.';
COMMENT ON COLUMN users.status                IS 'Auth gate: active | inactive | suspended.';
COMMENT ON COLUMN users.version               IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN users.deleted_at            IS 'Soft-delete timestamp. NULL = live row.';
