-- ============================================================
-- V31__create_tokens.sql
-- Queue token system. One token per patient per service per visit.
-- service_type drives which parent_id column is non-NULL (exactly
-- one per row — enforced by chk_tokens_exactly_one_parent).
-- FKs to lab_orders, radiology_orders, pharmacy_sales, and invoices
-- are deferred — added via ALTER TABLE in each module's migration.
-- ============================================================

CREATE TABLE tokens (

    id              uuid        NOT NULL DEFAULT uuidv7(),

    -- Display token (e.g. C-001, L-015, P-042) — generated by service layer
    token_number    text        NOT NULL,

    -- Monotonic counter per (service_type, provider_id, issue_date)
    token_sequence  int         NOT NULL,

    service_type    text        NOT NULL,

    -- For consultation: the assigned doctor. NULL for shared queues (lab, pharmacy, billing, radiology)
    provider_id     uuid,

    issue_date      date        NOT NULL,

    -- ── Polymorphic parent reference — exactly one must be non-NULL ──
    -- op_visit_id: set when service_type = 'consultation'
    op_visit_id             uuid,
    -- lab_order_id: set when service_type = 'lab' — FK added in lab module migration
    lab_order_id            uuid,
    -- radiology_order_id: set when service_type = 'radiology' — FK added in radiology module migration
    radiology_order_id      uuid,
    -- pharmacy_sale_id: set when service_type = 'pharmacy' — FK added in pharmacy module migration
    pharmacy_sale_id        uuid,
    -- invoice_id: set when service_type = 'billing' — FK added in billing module migration
    invoice_id              uuid,

    status          text        NOT NULL DEFAULT 'active',
    issued_by       uuid,
    called_at       timestamptz,
    completed_at    timestamptz,

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by      uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    version         int         NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    deleted_by      uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_tokens
        PRIMARY KEY (id),

    CONSTRAINT chk_tokens_service_type
        CHECK (service_type IN ('consultation','lab','pharmacy','radiology','billing')),

    CONSTRAINT chk_tokens_status
        CHECK (status IN ('active','called','completed','cancelled','no_show')),

    CONSTRAINT chk_tokens_sequence
        CHECK (token_sequence > 0),

    -- Exactly one parent reference must be populated per row
    CONSTRAINT chk_tokens_exactly_one_parent
        CHECK (num_nonnulls(op_visit_id, lab_order_id, radiology_order_id, pharmacy_sale_id, invoice_id) = 1),

    -- service_type ↔ parent column cross-checks
    CONSTRAINT chk_tokens_consultation_fk
        CHECK ((service_type = 'consultation') = (op_visit_id IS NOT NULL)),

    CONSTRAINT chk_tokens_lab_fk
        CHECK ((service_type = 'lab') = (lab_order_id IS NOT NULL)),

    CONSTRAINT chk_tokens_radiology_fk
        CHECK ((service_type = 'radiology') = (radiology_order_id IS NOT NULL)),

    CONSTRAINT chk_tokens_pharmacy_fk
        CHECK ((service_type = 'pharmacy') = (pharmacy_sale_id IS NOT NULL)),

    CONSTRAINT chk_tokens_billing_fk
        CHECK ((service_type = 'billing') = (invoice_id IS NOT NULL)),

    -- FK constraints for references whose target tables exist now
    CONSTRAINT fk_tokens_provider
        FOREIGN KEY (provider_id) REFERENCES users(id) ON DELETE SET NULL,

    CONSTRAINT fk_tokens_op_visit
        FOREIGN KEY (op_visit_id) REFERENCES op_visits(id) ON DELETE RESTRICT,

    CONSTRAINT fk_tokens_issued_by
        FOREIGN KEY (issued_by) REFERENCES users(id) ON DELETE SET NULL
);

-- ── Indexes ───────────────────────────────────────────────────

-- Sequence uniqueness per (service, doctor, date) when a specific provider is assigned
CREATE UNIQUE INDEX uq_tokens_with_provider
    ON tokens (service_type, provider_id, issue_date, token_sequence)
    WHERE provider_id IS NOT NULL;

-- Sequence uniqueness per (service, date) for shared queues (no provider)
CREATE UNIQUE INDEX uq_tokens_no_provider
    ON tokens (service_type, issue_date, token_sequence)
    WHERE provider_id IS NULL;

-- Resolve all tokens for a visit (patient token history within a visit)
CREATE INDEX ix_tokens_op_visit
    ON tokens (op_visit_id)
    WHERE op_visit_id IS NOT NULL;

-- Live queue display — active and called tokens for a service/provider today
CREATE INDEX ix_tokens_live_queue
    ON tokens (service_type, provider_id, status, issue_date)
    WHERE status IN ('active','called');

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_tokens_bu_touch
    BEFORE UPDATE ON tokens
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_tokens_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON tokens
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  tokens IS 'Queue token issued to a patient per service per visit. Exactly one of (op_visit_id, lab_order_id, radiology_order_id, pharmacy_sale_id, invoice_id) is non-NULL — enforced by chk_tokens_exactly_one_parent. FKs to lab_orders, radiology_orders, pharmacy_sales, and invoices are added via ALTER TABLE in their respective module migrations.';
COMMENT ON COLUMN tokens.token_number      IS 'Display token shown to patient (e.g. C-001 for consultation, L-015 for lab). Generated by service layer.';
COMMENT ON COLUMN tokens.token_sequence    IS 'Monotonic counter per (service_type, provider_id, issue_date). Drives token_number generation. Must be > 0.';
COMMENT ON COLUMN tokens.service_type      IS 'consultation | lab | pharmacy | radiology | billing. Determines which parent_id column is non-NULL.';
COMMENT ON COLUMN tokens.provider_id       IS 'Assigned doctor for consultation tokens. NULL for shared queues (lab, pharmacy, radiology, billing).';
COMMENT ON COLUMN tokens.issue_date        IS 'Calendar date on which the token was issued. Used for daily sequence reset and unique index scope.';
COMMENT ON COLUMN tokens.op_visit_id       IS 'Non-NULL when service_type = consultation. FK → op_visits(id).';
COMMENT ON COLUMN tokens.lab_order_id      IS 'Non-NULL when service_type = lab. FK added in lab module migration.';
COMMENT ON COLUMN tokens.radiology_order_id IS 'Non-NULL when service_type = radiology. FK added in radiology module migration.';
COMMENT ON COLUMN tokens.pharmacy_sale_id  IS 'Non-NULL when service_type = pharmacy. FK added in pharmacy module migration.';
COMMENT ON COLUMN tokens.invoice_id        IS 'Non-NULL when service_type = billing. FK added in billing module migration.';
COMMENT ON COLUMN tokens.status            IS 'active | called | completed | cancelled | no_show. Terminal states: completed, cancelled, no_show.';
COMMENT ON COLUMN tokens.issued_by         IS 'Staff member who issued the token. NULL for self-service kiosk or app-issued tokens.';
COMMENT ON COLUMN tokens.called_at         IS 'Timestamp when the token was called at the counter (status → called).';
COMMENT ON COLUMN tokens.completed_at      IS 'Timestamp when the service was completed (status → completed).';
COMMENT ON COLUMN tokens.version           IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN tokens.deleted_at        IS 'Soft-delete timestamp. NULL = live row.';
