-- ============================================================
-- V41__create_lab_orders.sql
-- Lab order header. One row per lab order raised by a doctor.
-- order_number is app-generated (e.g. LB-2026-00123).
-- status tracks the full lifecycle: ordered → sample collection
-- → result entry → release.
-- invoice_id FK to invoices(id) deferred to billing module (Module 17).
-- Also wires deferred FKs from tokens and doctor_recommendations.
-- ============================================================

CREATE TABLE lab_orders (

    id              uuid        NOT NULL DEFAULT uuidv7(),

    -- Human-readable reference printed on sample labels and reports
    order_number    text        NOT NULL,

    patient_id      uuid        NOT NULL,

    -- NULL for orders raised outside a formal OP visit
    op_visit_id     uuid,

    -- NULL when the order is not linked to a consultation note
    consultation_id uuid,

    -- Ordering clinician
    doctor_id       uuid        NOT NULL,

    -- Urgency level drives worklist ordering and SLA targets
    priority        text        NOT NULL DEFAULT 'routine',

    -- Full lifecycle state machine
    status          text        NOT NULL DEFAULT 'ordered',

    -- Billing reference — FK to invoices(id) added in billing module migration (Module 17)
    invoice_id      uuid,

    -- Populated when the last test result is released
    completed_at    timestamptz,

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by      uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    version         int         NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    deleted_by      uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_lab_orders
        PRIMARY KEY (id),

    CONSTRAINT uq_lab_orders_number
        UNIQUE (order_number),

    CONSTRAINT fk_lab_orders_patient
        FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT,

    CONSTRAINT fk_lab_orders_visit
        FOREIGN KEY (op_visit_id) REFERENCES op_visits(id) ON DELETE RESTRICT,

    CONSTRAINT fk_lab_orders_consultation
        FOREIGN KEY (consultation_id) REFERENCES consultations(id) ON DELETE RESTRICT,

    CONSTRAINT fk_lab_orders_doctor
        FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_lab_orders_priority
        CHECK (priority IN ('routine','urgent','stat')),

    CONSTRAINT chk_lab_orders_status
        CHECK (status IN (
            'ordered','paid','sample_collection','sample_collected',
            'in_progress','partially_reported','reported','released','cancelled'
        ))
);

-- ── Indexes ───────────────────────────────────────────────────

-- Patient lab history ordered by most recent first
CREATE INDEX ix_lab_orders_patient
    ON lab_orders (patient_id, created_at DESC)
    WHERE deleted_at IS NULL;

-- Lab worklist — pending and in-progress orders sorted by urgency then arrival
CREATE INDEX ix_lab_orders_worklist
    ON lab_orders (status, priority, created_at)
    WHERE deleted_at IS NULL;

-- Lookup all lab orders for an OP visit
CREATE INDEX ix_lab_orders_visit
    ON lab_orders (op_visit_id)
    WHERE op_visit_id IS NOT NULL AND deleted_at IS NULL;

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_lab_orders_bu_touch
    BEFORE UPDATE ON lab_orders
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_lab_orders_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON lab_orders
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  lab_orders IS 'Lab order header. invoice_id FK added in billing module. status tracks the full lifecycle from ordering through sample collection to result release.';
COMMENT ON COLUMN lab_orders.order_number    IS 'Human-readable reference printed on sample labels and result reports (e.g. LB-2026-00123). Globally unique. Generated by service layer.';
COMMENT ON COLUMN lab_orders.patient_id      IS 'Patient for whom the lab order was raised.';
COMMENT ON COLUMN lab_orders.op_visit_id     IS 'OP visit that triggered the order. NULL for orders raised outside a formal visit (e.g. direct walk-in lab requests).';
COMMENT ON COLUMN lab_orders.consultation_id IS 'Consultation note that generated this order. NULL when raised without a consultation (e.g. direct lab walk-in).';
COMMENT ON COLUMN lab_orders.doctor_id       IS 'Clinician who ordered the tests. Required even for walk-in orders (requisition must carry a doctor signature).';
COMMENT ON COLUMN lab_orders.priority        IS 'routine | urgent | stat. Drives worklist ordering and SLA targets.';
COMMENT ON COLUMN lab_orders.status          IS 'ordered → paid → sample_collection → sample_collected → in_progress → partially_reported → reported → released. cancelled is a terminal state.';
COMMENT ON COLUMN lab_orders.invoice_id      IS 'FK → invoices(id) RESTRICT — constraint added in the billing module migration (Module 17).';
COMMENT ON COLUMN lab_orders.completed_at    IS 'Timestamp when the last test result was released (status → released). NULL while the order is still in progress.';
COMMENT ON COLUMN lab_orders.version         IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN lab_orders.deleted_at      IS 'Soft-delete timestamp. NULL = live row.';

-- ── Wire deferred FKs now that lab_orders exists ──────────────

-- tokens.lab_order_id was left without an FK in V31 because lab_orders
-- did not exist yet. Wire it now.
ALTER TABLE tokens
    ADD CONSTRAINT fk_tokens_lab_order
    FOREIGN KEY (lab_order_id) REFERENCES lab_orders(id) ON DELETE RESTRICT;

-- doctor_recommendations.lab_order_id was left without an FK in V37 for
-- the same reason. Wire it now.
ALTER TABLE doctor_recommendations
    ADD CONSTRAINT fk_doctor_recommendations_lab_order
    FOREIGN KEY (lab_order_id) REFERENCES lab_orders(id) ON DELETE RESTRICT;
