-- ============================================================
-- V52__create_purchase_orders.sql
-- Purchase order header sent to a vendor.
-- L2 maker-checker: the user who drafted the PO (created_by)
-- cannot be the same as approved_by — enforced by
-- chk_purchase_orders_sod (segregation of duties).
-- includes_narcotics and total_amount are recomputed by the
-- fn_recompute_po_totals() trigger defined in V53 on
-- purchase_order_items changes.
-- Soft-delete via deleted_at (full 7 audit).
-- ============================================================

CREATE TABLE purchase_orders (

    id                  uuid            NOT NULL DEFAULT uuidv7(),

    -- Human-readable PO reference (e.g. PO-2026-00001)
    po_number           text            NOT NULL,

    vendor_id           uuid            NOT NULL,

    -- Expected delivery date; NULL when not yet confirmed
    expected_date       date,

    -- Lifecycle status of the PO
    status              text            NOT NULL DEFAULT 'draft',

    -- Running total recomputed by trigger on line-item changes
    total_amount        numeric(14,2)   NOT NULL DEFAULT 0,

    -- Timestamp when the last GRN closed the PO (status → received)
    received_at         timestamptz,

    -- Auto-set to true by fn_recompute_po_totals() when any
    -- line item contains a narcotic drug
    includes_narcotics  boolean         NOT NULL DEFAULT false,

    -- ── L2 maker-checker columns ─────────────────────────────
    -- Drafter submits for approval; a different user must approve

    approval_status     text            NOT NULL DEFAULT 'pending_approval',

    -- Staff member who approved or rejected the PO
    approved_by         uuid,

    approved_at         timestamptz,

    -- Reason provided when approval_status = 'rejected'
    rejection_reason    text,

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by          uuid            NOT NULL,
    created_at          timestamptz     NOT NULL DEFAULT now(),
    updated_by          uuid,
    updated_at          timestamptz     NOT NULL DEFAULT now(),
    version             int             NOT NULL DEFAULT 0,
    deleted_at          timestamptz,
    deleted_by          uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_purchase_orders
        PRIMARY KEY (id),

    CONSTRAINT uq_purchase_orders_number
        UNIQUE (po_number),

    CONSTRAINT fk_purchase_orders_vendor
        FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE RESTRICT,

    CONSTRAINT fk_purchase_orders_approved_by
        FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_purchase_orders_number_len
        CHECK (char_length(po_number) BETWEEN 5 AND 30),

    CONSTRAINT chk_purchase_orders_status
        CHECK (status IN ('draft','pending_approval','approved','sent','partially_received','received','cancelled','rejected')),

    CONSTRAINT chk_purchase_orders_total
        CHECK (total_amount >= 0),

    CONSTRAINT chk_purchase_orders_approval_status
        CHECK (approval_status IN ('pending_approval','approved','rejected')),

    -- Segregation of duties: drafter cannot approve their own PO
    CONSTRAINT chk_purchase_orders_sod
        CHECK (created_by <> approved_by OR approved_by IS NULL)
);

-- ── Indexes ───────────────────────────────────────────────────

-- Operations worklist: open POs by status, newest first
CREATE INDEX ix_purchase_orders_pending
    ON purchase_orders (status, created_at DESC)
    WHERE status IN ('pending_approval','approved','sent','partially_received') AND deleted_at IS NULL;

-- Vendor order history
CREATE INDEX ix_purchase_orders_vendor
    ON purchase_orders (vendor_id, status)
    WHERE deleted_at IS NULL;

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_purchase_orders_bu_touch
    BEFORE UPDATE ON purchase_orders
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_purchase_orders_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON purchase_orders
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  purchase_orders IS 'Purchase order to a vendor. L2 maker-checker: drafter cannot approve their own PO (chk_purchase_orders_sod). includes_narcotics and total_amount are recomputed by trigger on purchase_order_items changes.';
COMMENT ON COLUMN purchase_orders.po_number          IS 'Human-readable PO reference (e.g. PO-2026-00001). Globally unique. Generated by service layer.';
COMMENT ON COLUMN purchase_orders.vendor_id          IS 'Supplying vendor. ON DELETE RESTRICT — POs are retained even if a vendor is soft-deleted.';
COMMENT ON COLUMN purchase_orders.expected_date      IS 'Expected delivery date communicated to the vendor. NULL when not yet confirmed.';
COMMENT ON COLUMN purchase_orders.status             IS 'Lifecycle: draft → pending_approval → approved → sent → partially_received → received | cancelled | rejected.';
COMMENT ON COLUMN purchase_orders.total_amount       IS 'Sum of purchase_order_items.total_price. Auto-recomputed by fn_recompute_po_totals() trigger. Must be >= 0.';
COMMENT ON COLUMN purchase_orders.received_at        IS 'Timestamp when all items were received and status moved to received.';
COMMENT ON COLUMN purchase_orders.includes_narcotics IS 'Auto-set to true by fn_recompute_po_totals() trigger when any line item is a narcotic drug. Triggers narcotic purchase controls.';
COMMENT ON COLUMN purchase_orders.approval_status    IS 'L2 state: pending_approval | approved | rejected. Distinct from status to allow independent lifecycle tracking.';
COMMENT ON COLUMN purchase_orders.approved_by        IS 'User who approved or rejected the PO. Must differ from created_by (chk_purchase_orders_sod).';
COMMENT ON COLUMN purchase_orders.approved_at        IS 'Timestamp of approval or rejection.';
COMMENT ON COLUMN purchase_orders.rejection_reason   IS 'Mandatory written reason when approval_status = rejected.';
COMMENT ON COLUMN purchase_orders.version            IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN purchase_orders.deleted_at         IS 'Soft-delete timestamp. NULL = live row.';
