-- ============================================================
-- V57__create_pharmacy_sales.sql
-- Pharmacy sale header. One row per dispensing transaction.
-- sale_number generated by the service layer (e.g. RX-2026-00101).
-- invoice_id FK deferred to billing module migration (Module 17).
-- cash_session_id FK deferred to payments module migration (Module 18).
-- Also wires deferred FKs from tokens.pharmacy_sale_id and
-- narcotic_register.pharmacy_sale_id.
-- Walk-in sales may have customer_name/mobile without a patients row.
-- ============================================================

CREATE TABLE pharmacy_sales (

    id                          uuid            NOT NULL DEFAULT uuidv7(),

    -- Human-readable sale reference — generated by service layer
    sale_number                 text            NOT NULL,

    -- NULL for walk-in sales without a patient record
    patient_id                  uuid,

    -- op_patient | ip_patient | walkin_prescription | walkin_otc | staff_self
    sale_type                   text            NOT NULL,

    -- Linked prescription from the consultation module; NULL for OTC
    prescription_id             uuid,

    -- External (paper) prescription reference for walkin_prescription sales
    external_prescription_ref   text,

    -- Walk-in patient details — used when patient_id is NULL
    customer_name               text,
    customer_mobile             text,
    customer_age                int,

    -- FK → invoices(id) added in billing module migration (Module 17)
    invoice_id                  uuid,

    -- FK → cash_sessions(id) added in payments module migration (Module 18)
    cash_session_id             uuid,

    -- Financial summary — recomputed by service layer from sale items
    subtotal                    numeric(14,2)   NOT NULL DEFAULT 0,
    total_tax                   numeric(14,2)   NOT NULL DEFAULT 0,

    -- Bill-level discount — either percentage or flat amount
    bill_discount_pct           numeric(4,2),
    bill_discount_amount        numeric(14,2)   NOT NULL DEFAULT 0,
    bill_discount_approved_by   uuid,
    bill_discount_reason        text,

    net_amount                  numeric(14,2)   NOT NULL DEFAULT 0,

    -- draft | billed | dispensed | partially_dispensed | cancelled | returned
    status                      text            NOT NULL DEFAULT 'draft',

    -- Client-generated UUID to prevent duplicate sale creation on network retries
    idempotency_key             uuid,

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by      uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    version         int         NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    deleted_by      uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_pharmacy_sales
        PRIMARY KEY (id),

    CONSTRAINT uq_pharmacy_sales_number
        UNIQUE (sale_number),

    CONSTRAINT fk_pharmacy_sales_patient
        FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT,

    CONSTRAINT fk_pharmacy_sales_prescription
        FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE RESTRICT,

    CONSTRAINT fk_pharmacy_sales_discount_approver
        FOREIGN KEY (bill_discount_approved_by) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_pharmacy_sales_number_len
        CHECK (char_length(sale_number) BETWEEN 5 AND 30),

    CONSTRAINT chk_pharmacy_sales_type
        CHECK (sale_type IN ('op_patient','ip_patient','walkin_prescription','walkin_otc','staff_self')),

    CONSTRAINT chk_pharmacy_sales_status
        CHECK (status IN ('draft','billed','dispensed','partially_dispensed','cancelled','returned')),

    CONSTRAINT chk_pharmacy_sales_discount_pct
        CHECK (bill_discount_pct IS NULL OR (bill_discount_pct > 0 AND bill_discount_pct <= 100)),

    CONSTRAINT chk_pharmacy_sales_amounts
        CHECK (subtotal >= 0 AND total_tax >= 0 AND bill_discount_amount >= 0 AND net_amount >= 0),

    CONSTRAINT chk_pharmacy_sales_customer_mobile
        CHECK (customer_mobile IS NULL OR char_length(customer_mobile) BETWEEN 10 AND 15),

    CONSTRAINT chk_pharmacy_sales_customer_age
        CHECK (customer_age IS NULL OR customer_age > 0)
);

-- ── Indexes ───────────────────────────────────────────────────

-- Patient dispensing history — newest first (primary patient lookup)
CREATE INDEX ix_pharmacy_sales_patient
    ON pharmacy_sales (patient_id, created_at DESC)
    WHERE patient_id IS NOT NULL AND deleted_at IS NULL;

-- Operational status queue — open/draft sales by date
CREATE INDEX ix_pharmacy_sales_status
    ON pharmacy_sales (status, created_at DESC)
    WHERE deleted_at IS NULL;

-- Prescription fulfilment lookup
CREATE INDEX ix_pharmacy_sales_prescription
    ON pharmacy_sales (prescription_id)
    WHERE prescription_id IS NOT NULL AND deleted_at IS NULL;

-- Partial unique index — idempotency key uniqueness only when present
CREATE UNIQUE INDEX uq_pharmacy_sales_idempotency
    ON pharmacy_sales (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_pharmacy_sales_bu_touch
    BEFORE UPDATE ON pharmacy_sales
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_pharmacy_sales_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON pharmacy_sales
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  pharmacy_sales IS 'Pharmacy sale header. invoice_id FK added in billing module. cash_session_id FK added in payments module. Walk-in sales may have customer_name/mobile without a patients row.';
COMMENT ON COLUMN pharmacy_sales.sale_number                IS 'Human-readable sale reference (e.g. RX-2026-00101). Globally unique. Generated by service layer.';
COMMENT ON COLUMN pharmacy_sales.patient_id                 IS 'Registered patient linked to this sale. NULL for anonymous walk-in customers.';
COMMENT ON COLUMN pharmacy_sales.sale_type                  IS 'op_patient | ip_patient | walkin_prescription | walkin_otc | staff_self. Determines workflow and stock-dispensing rules.';
COMMENT ON COLUMN pharmacy_sales.prescription_id            IS 'Linked prescription from the consultation module. NULL for OTC walk-in sales.';
COMMENT ON COLUMN pharmacy_sales.external_prescription_ref  IS 'Reference number of a paper prescription from an external provider. Used for walkin_prescription type.';
COMMENT ON COLUMN pharmacy_sales.customer_name              IS 'Full name of a walk-in customer who has no patient record. NULL when patient_id is set.';
COMMENT ON COLUMN pharmacy_sales.customer_mobile            IS 'Contact mobile number of the walk-in customer. 10–15 characters when present.';
COMMENT ON COLUMN pharmacy_sales.customer_age               IS 'Age of the walk-in customer in years. Must be > 0 when present.';
COMMENT ON COLUMN pharmacy_sales.invoice_id                 IS 'FK → invoices(id) RESTRICT — constraint added in billing module migration (Module 17).';
COMMENT ON COLUMN pharmacy_sales.cash_session_id            IS 'FK → cash_sessions(id) RESTRICT — constraint added in payments module migration (Module 18).';
COMMENT ON COLUMN pharmacy_sales.subtotal                   IS 'Sum of (unit_price × quantity) across all sale items before discount and tax. Recomputed by service layer.';
COMMENT ON COLUMN pharmacy_sales.total_tax                  IS 'Total GST (CGST + SGST or IGST) across all sale items. Recomputed by service layer.';
COMMENT ON COLUMN pharmacy_sales.bill_discount_pct          IS 'Bill-level discount percentage (> 0 and <= 100). NULL means no percentage discount applied.';
COMMENT ON COLUMN pharmacy_sales.bill_discount_amount       IS 'Flat bill-level discount amount derived from bill_discount_pct or entered directly.';
COMMENT ON COLUMN pharmacy_sales.bill_discount_approved_by  IS 'User who authorised the bill-level discount. Required for discounts above the configured threshold.';
COMMENT ON COLUMN pharmacy_sales.bill_discount_reason       IS 'Free-text reason for the bill-level discount. Used for audit and reporting.';
COMMENT ON COLUMN pharmacy_sales.net_amount                 IS 'Final payable amount: subtotal + total_tax − bill_discount_amount. Must be >= 0.';
COMMENT ON COLUMN pharmacy_sales.status                     IS 'draft | billed | dispensed | partially_dispensed | cancelled | returned. Terminal states: cancelled, returned.';
COMMENT ON COLUMN pharmacy_sales.idempotency_key            IS 'Client-generated UUID to prevent duplicate sale creation on network retries. Partial unique index ensures uniqueness only when present.';
COMMENT ON COLUMN pharmacy_sales.version                    IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN pharmacy_sales.deleted_at                 IS 'Soft-delete timestamp. NULL = live row.';

-- ── Deferred FKs from tokens and narcotic_register ───────────

-- tokens.pharmacy_sale_id was left as a plain uuid column in V31
-- (pharmacy_sales did not exist at that point). Wire it now.

ALTER TABLE tokens
    ADD CONSTRAINT fk_tokens_pharmacy_sale
    FOREIGN KEY (pharmacy_sale_id) REFERENCES pharmacy_sales(id) ON DELETE RESTRICT;

-- narcotic_register.pharmacy_sale_id was left as a plain uuid column in V56
-- (pharmacy_sales did not exist at that point). Wire it now.

ALTER TABLE narcotic_register
    ADD CONSTRAINT fk_narcotic_register_sale
    FOREIGN KEY (pharmacy_sale_id) REFERENCES pharmacy_sales(id) ON DELETE RESTRICT;
