-- ============================================================
-- V59__create_pharmacy_returns.sql
-- Pharmacy return transaction header. One row per return event,
-- which may cover a full or partial reversal of a prior sale.
-- return_number generated by the service layer (e.g. RTN-2026-00001).
-- cash_session_id FK deferred to payments module migration (Module 18).
-- total_return_amount is recomputed by the service layer from
-- pharmacy_return_items; the column is kept here for quick reporting.
-- ============================================================

CREATE TABLE pharmacy_returns (

    id                      uuid            NOT NULL DEFAULT uuidv7(),

    -- Human-readable return reference — generated by service layer
    return_number           text            NOT NULL,

    -- The original sale being reversed (full or partial)
    original_sale_id        uuid            NOT NULL,

    -- Registered patient linked to the original sale; NULL for walk-in
    patient_id              uuid,

    -- Walk-in customer details (mirrors pharmacy_sales)
    customer_name           text,
    customer_mobile         text,

    -- full = entire sale returned; partial = subset of items returned
    return_type             text            NOT NULL,

    -- Mandatory free-text reason for the return (regulatory requirement)
    return_reason           text            NOT NULL,

    -- Total refund amount — recomputed by service layer from return items
    total_return_amount     numeric(14,2)   NOT NULL DEFAULT 0,

    -- FK → cash_sessions(id) added in payments module migration (Module 18)
    cash_session_id         uuid,

    -- Staff member who processed the return at the counter
    processed_by            uuid            NOT NULL,
    processed_at            timestamptz     NOT NULL DEFAULT now(),

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by      uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    version         int         NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    deleted_by      uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_pharmacy_returns
        PRIMARY KEY (id),

    CONSTRAINT uq_pharmacy_returns_number
        UNIQUE (return_number),

    CONSTRAINT fk_pharmacy_returns_sale
        FOREIGN KEY (original_sale_id) REFERENCES pharmacy_sales(id) ON DELETE RESTRICT,

    CONSTRAINT fk_pharmacy_returns_patient
        FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT,

    CONSTRAINT fk_pharmacy_returns_processed_by
        FOREIGN KEY (processed_by) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_pharmacy_returns_number_len
        CHECK (char_length(return_number) BETWEEN 5 AND 30),

    CONSTRAINT chk_pharmacy_returns_type
        CHECK (return_type IN ('full','partial')),

    CONSTRAINT chk_pharmacy_returns_amount
        CHECK (total_return_amount >= 0),

    CONSTRAINT chk_pharmacy_returns_customer_mobile
        CHECK (customer_mobile IS NULL OR char_length(customer_mobile) BETWEEN 10 AND 15)
);

-- ── Indexes ───────────────────────────────────────────────────

-- Return history for a sale — key for double-return guard in service layer
CREATE INDEX ix_pharmacy_returns_sale
    ON pharmacy_returns (original_sale_id)
    WHERE deleted_at IS NULL;

-- Daily / shift return report ordered by processing time
CREATE INDEX ix_pharmacy_returns_date
    ON pharmacy_returns (processed_at DESC)
    WHERE deleted_at IS NULL;

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_pharmacy_returns_bu_touch
    BEFORE UPDATE ON pharmacy_returns
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_pharmacy_returns_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON pharmacy_returns
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  pharmacy_returns IS 'Pharmacy return header. cash_session_id FK added in payments module. total_return_amount is recomputed by service layer from pharmacy_return_items.';
COMMENT ON COLUMN pharmacy_returns.return_number        IS 'Human-readable return reference (e.g. RTN-2026-00001). Globally unique. Generated by service layer.';
COMMENT ON COLUMN pharmacy_returns.original_sale_id     IS 'The pharmacy_sales row being reversed. FK → pharmacy_sales(id) RESTRICT.';
COMMENT ON COLUMN pharmacy_returns.patient_id           IS 'Registered patient linked to the original sale. NULL for walk-in customers.';
COMMENT ON COLUMN pharmacy_returns.customer_name        IS 'Full name of a walk-in customer. NULL when patient_id is set.';
COMMENT ON COLUMN pharmacy_returns.customer_mobile      IS 'Contact mobile number of the walk-in customer. 10–15 characters when present.';
COMMENT ON COLUMN pharmacy_returns.return_type          IS 'full = entire sale returned; partial = subset of items returned.';
COMMENT ON COLUMN pharmacy_returns.return_reason        IS 'Mandatory free-text reason for the return. Used for audit and regulatory reporting.';
COMMENT ON COLUMN pharmacy_returns.total_return_amount  IS 'Total refund amount recomputed by service layer from pharmacy_return_items. Stored for quick reporting.';
COMMENT ON COLUMN pharmacy_returns.cash_session_id      IS 'FK → cash_sessions(id) RESTRICT — constraint added in payments module migration (Module 18).';
COMMENT ON COLUMN pharmacy_returns.processed_by         IS 'Staff member who processed the return at the counter. FK → users(id) RESTRICT.';
COMMENT ON COLUMN pharmacy_returns.processed_at         IS 'Timestamp when the return was processed. Defaults to now().';
COMMENT ON COLUMN pharmacy_returns.version              IS 'Optimistic-lock counter — owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN pharmacy_returns.deleted_at           IS 'Soft-delete timestamp. NULL = live row.';
