-- ============================================================
-- V66__create_cash_sessions.sql
-- Cashier shift record. One row per cash session at a counter.
-- status lifecycle: open → closed → reopened → closed → locked.
-- GENERATED variance = counted_cash - expected_cash (STORED).
-- denomination_breakdown jsonb captures coin/note counts at closure.
-- Also wires the deferred cash_session_id FKs on pharmacy_sales
-- and pharmacy_returns (plain uuid columns left in V57 and V59).
-- ============================================================

CREATE TABLE cash_sessions (

    id                      uuid            NOT NULL DEFAULT uuidv7(),

    -- The physical counter at which this session was opened
    counter_id              uuid            NOT NULL,

    -- Human-readable session identifier — generated by service layer
    session_number          text            NOT NULL,

    -- Shift label for this session
    session_label           text            NOT NULL,

    -- Calendar date this session belongs to (for daily reconciliation)
    business_date           date            NOT NULL,

    -- Cashier who opened this session
    opened_by               uuid            NOT NULL,
    opened_at               timestamptz     NOT NULL DEFAULT now(),

    -- Cashier who closed this session; NULL while session is open
    closed_by               uuid,
    closed_at               timestamptz,

    -- Current lifecycle state of the session
    status                  text            NOT NULL DEFAULT 'open',

    -- Cash float handed to the cashier at session open
    opening_float           numeric(14,2)   NOT NULL DEFAULT 0,

    -- Cash expected in the drawer based on transactions (computed at close)
    expected_cash           numeric(14,2),

    -- Physical cash counted in the drawer at close
    counted_cash            numeric(14,2),

    -- Difference between counted and expected; NULL until both values are set
    variance                numeric(14,2)   GENERATED ALWAYS AS (counted_cash - expected_cash) STORED,

    -- Mandatory explanation when variance is non-zero
    variance_reason         text,

    -- JSON map of note/coin denominations counted at session close
    denomination_breakdown  jsonb,

    -- Free-text notes recorded at session close
    closure_notes           text,

    -- ── Uniform audit + soft-delete block ────────────────────
    created_by      uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    version         int         NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    deleted_by      uuid,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_cash_sessions
        PRIMARY KEY (id),

    CONSTRAINT uq_cash_sessions_number
        UNIQUE (session_number),

    CONSTRAINT fk_cash_sessions_counter
        FOREIGN KEY (counter_id) REFERENCES cash_counters(id) ON DELETE RESTRICT,

    CONSTRAINT fk_cash_sessions_opened_by
        FOREIGN KEY (opened_by) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT fk_cash_sessions_closed_by
        FOREIGN KEY (closed_by) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_cash_sessions_number_len
        CHECK (char_length(session_number) BETWEEN 5 AND 30),

    CONSTRAINT chk_cash_sessions_label
        CHECK (session_label IN ('morning','evening','night','full_day','custom')),

    CONSTRAINT chk_cash_sessions_status
        CHECK (status IN ('open','closed','reopened','locked')),

    CONSTRAINT chk_cash_sessions_float
        CHECK (opening_float >= 0),

    -- closed_at must be present if and only if session is closed or locked
    CONSTRAINT chk_cash_sessions_closed_at_consistency
        CHECK ((status IN ('closed','locked')) = (closed_at IS NOT NULL)),

    -- A non-zero variance requires an explanation
    CONSTRAINT chk_cash_sessions_variance_reason
        CHECK (variance IS NULL OR variance = 0 OR variance_reason IS NOT NULL)
);

-- ── Indexes ───────────────────────────────────────────────────

-- Counter daily session list — newest date first
CREATE INDEX ix_cash_sessions_counter_date
    ON cash_sessions (counter_id, business_date DESC)
    WHERE deleted_at IS NULL;

-- Cashier session history — newest date first
CREATE INDEX ix_cash_sessions_opened_by
    ON cash_sessions (opened_by, business_date DESC)
    WHERE deleted_at IS NULL;

-- Status queue (e.g. find all open sessions for today)
CREATE INDEX ix_cash_sessions_status
    ON cash_sessions (status, business_date DESC)
    WHERE deleted_at IS NULL;

-- ── Triggers ──────────────────────────────────────────────────

-- Layer 1: bump updated_at on every UPDATE
CREATE TRIGGER tr_cash_sessions_bu_touch
    BEFORE UPDATE ON cash_sessions
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated();

-- Layer 3: full-row audit trail
CREATE TRIGGER tr_cash_sessions_au_audit
    AFTER INSERT OR UPDATE OR DELETE ON cash_sessions
    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  cash_sessions IS 'Cashier shift record. status: open → closed → reopened → closed → locked. GENERATED variance = counted_cash - expected_cash. denomintation_breakdown jsonb records coin/note counts at closure.';
COMMENT ON COLUMN cash_sessions.session_number         IS 'Human-readable session identifier (5–30 characters). Globally unique. Generated by service layer.';
COMMENT ON COLUMN cash_sessions.session_label          IS 'Shift label: morning | evening | night | full_day | custom.';
COMMENT ON COLUMN cash_sessions.business_date          IS 'Calendar date this session belongs to. Used for daily reconciliation grouping.';
COMMENT ON COLUMN cash_sessions.opened_by              IS 'Cashier who opened the session. FK → users(id) RESTRICT.';
COMMENT ON COLUMN cash_sessions.opened_at              IS 'Timestamp when the session was opened. Defaults to now().';
COMMENT ON COLUMN cash_sessions.closed_by              IS 'Cashier who closed the session. NULL while the session is open or reopened.';
COMMENT ON COLUMN cash_sessions.closed_at              IS 'Timestamp when the session was closed. Must be non-NULL when status is closed or locked.';
COMMENT ON COLUMN cash_sessions.status                 IS 'open | closed | reopened | locked. Locked sessions cannot be reopened.';
COMMENT ON COLUMN cash_sessions.opening_float          IS 'Cash float handed to the cashier at session open. Must be >= 0.';
COMMENT ON COLUMN cash_sessions.expected_cash          IS 'Cash amount expected in the drawer, computed from transactions at close. NULL until session is closed.';
COMMENT ON COLUMN cash_sessions.counted_cash           IS 'Physical cash counted in the drawer at close. NULL until session is closed.';
COMMENT ON COLUMN cash_sessions.variance               IS 'GENERATED ALWAYS AS (counted_cash - expected_cash) STORED. NULL until both expected_cash and counted_cash are set at closure.';
COMMENT ON COLUMN cash_sessions.variance_reason        IS 'Mandatory explanation when variance is non-zero. Enforced by chk_cash_sessions_variance_reason.';
COMMENT ON COLUMN cash_sessions.denomination_breakdown IS 'JSON map of note/coin denominations counted at session close: e.g. {"2000":2,"500":5,"100":10,"50":4}.';
COMMENT ON COLUMN cash_sessions.closure_notes          IS 'Optional free-text notes recorded by the cashier at session close.';
COMMENT ON COLUMN cash_sessions.version                IS 'Owned by Hibernate @Version. Trigger does NOT touch this column.';
COMMENT ON COLUMN cash_sessions.deleted_at             IS 'Soft-delete timestamp. NULL = live session.';

-- ── Deferred cash_session_id FKs ─────────────────────────────
-- Wire deferred cash_session_id FKs now that cash_sessions exists.
-- pharmacy_sales.cash_session_id was left as a plain uuid column in V57.
-- pharmacy_returns.cash_session_id was left as a plain uuid column in V59.

ALTER TABLE pharmacy_sales
    ADD CONSTRAINT fk_pharmacy_sales_cash_session
    FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id) ON DELETE RESTRICT;

ALTER TABLE pharmacy_returns
    ADD CONSTRAINT fk_pharmacy_returns_cash_session
    FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id) ON DELETE RESTRICT;
