import { mockDoctor } from '@/features/auth/__mocks__/authMocks';
import type { EncounterStatus, EncounterStatusName } from '@/features/encounter';
import type {
  ConsultationContext,
  ConsultationNote,
  Diagnosis,
  PrescriptionItem,
  PrescriptionTemplate,
  Vitals,
} from '../consultationTypes';
import type { LabOrder } from '@/features/lab';
import type { Modality, RadiologyOrder } from '@/features/radiology';
import { findPatient, mockPatients } from '@/features/patient/__mocks__/patientMocks';
import type { PatientSummary } from '@/features/patient';

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 *  Mock past-encounter generator
 *  --------------------------------------------------------------------------
 *  `mockPastEncounters` is the master source for everything visit-history-
 *  related. We derive `VisitHistoryItem[]` from it in `consultationApi.ts`,
 *  and `mockPastOpVisits` / `mockOpVisitDoctor` in `encounterMocks.ts`.
 *
 *  Each encounter is generated by combining:
 *    - a clinical TEMPLATE (chief complaint + notes + diagnoses + Rx +
 *      labs + radiology),
 *    - a PATIENT PROFILE (the patient + which doctor sees them),
 *    - a VISIT DATE.
 *
 *  The chip/badge on a visit-history row therefore always matches what the
 *  consultation page actually contains â€” they share a single record.
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */

/** Mock-only status factory; real backend issues `code` from `patient_states`. */
const status = (name: EncounterStatusName): EncounterStatus => ({ code: 0, name });

const PDF_LAB = (opNumber: string, testCode: string): string =>
  `/mock-reports/lab/${testCode}-${opNumber}.pdf`;
const PDF_RAD = (opNumber: string, testCode: string): string =>
  `/mock-reports/radiology/${testCode}-${opNumber}.pdf`;

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 *  Doctor roster (mirrors `sharedDoctors` in appointmentsMocks)
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */

interface DoctorRef { id: string; name: string; department: string; }

const DR_NAVEEN:  DoctorRef = { id: 'usr-doc-001', name: 'Dr. Naveen Kumar', department: 'Orthopaedics' };
const DR_ANAND:   DoctorRef = { id: 'usr-doc-002', name: 'Dr. Anand', department: 'General Medicine' };
const DR_MEERA:   DoctorRef = { id: 'usr-doc-003', name: 'Dr. Meera',   department: 'Dental' };
const DR_LAKSHMI: DoctorRef = { id: 'usr-doc-004', name: 'Dr. Lakshmi',   department: 'Obstetrics & Gynaecology' };
const DR_RAVI:    DoctorRef = { id: 'usr-doc-005', name: 'Dr. Ravi',   department: 'Physiotherapy' };

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 *  Encounter templates â€” clinical archetypes that drive each visit
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */

interface RxSeed {
  medicineId: string;
  name: string;
  strength: string;
  dosage: string;
  frequency: string;
  route: string;
  days: number;
  instructions: string;
}

interface LabSeed {
  testCode: string;
  testName: string;
  resultSummary: string;
  flag?: LabOrder['flag'];
}

interface RadSeed {
  testCode: string;
  testName: string;
  modality: Modality;
  resultSummary: string;
}

interface EncounterTemplate {
  doctor: DoctorRef;
  notes: ConsultationNote;
  diagnoses: Array<Omit<Diagnosis, 'id'>>;
  prescriptions: RxSeed[];
  labs: LabSeed[];
  radiology: RadSeed[];
}

/* --- Rx building blocks (compact, real-world combinations) --- */

const RX_PARACETAMOL: RxSeed = { medicineId: 'med-100', name: 'Paracetamol', strength: '500 mg', dosage: '1 tab', frequency: 'TDS', route: 'PO', days: 5, instructions: 'After food' };
const RX_IBUPROFEN:   RxSeed = { medicineId: 'med-101', name: 'Ibuprofen',   strength: '400 mg', dosage: '1 tab', frequency: 'BD',  route: 'PO', days: 5, instructions: 'After food' };
const RX_PANTOPRAZOLE: RxSeed = { medicineId: 'med-140', name: 'Pantoprazole', strength: '40 mg', dosage: '1 tab', frequency: 'OD', route: 'PO', days: 7, instructions: 'Before breakfast' };
const RX_AMLODIPINE:  RxSeed = { medicineId: 'med-200', name: 'Amlodipine',  strength: '5 mg',   dosage: '1 tab', frequency: 'OD', route: 'PO', days: 30, instructions: 'Morning, after food' };
const RX_TELMISARTAN: RxSeed = { medicineId: 'med-201', name: 'Telmisartan', strength: '40 mg',  dosage: '1 tab', frequency: 'OD', route: 'PO', days: 30, instructions: 'Morning' };
const RX_METFORMIN:   RxSeed = { medicineId: 'med-300', name: 'Metformin',   strength: '500 mg', dosage: '1 tab', frequency: 'BD', route: 'PO', days: 30, instructions: 'After meals' };
const RX_GLIMEPIRIDE: RxSeed = { medicineId: 'med-301', name: 'Glimepiride', strength: '2 mg',   dosage: '1 tab', frequency: 'OD', route: 'PO', days: 30, instructions: 'Before breakfast' };
const RX_ATORVASTATIN: RxSeed = { medicineId: 'med-310', name: 'Atorvastatin', strength: '10 mg', dosage: '1 tab', frequency: 'HS', route: 'PO', days: 30, instructions: 'At bedtime' };
const RX_ASPIRIN:     RxSeed = { medicineId: 'med-320', name: 'Aspirin',     strength: '75 mg',  dosage: '1 tab', frequency: 'OD', route: 'PO', days: 30, instructions: 'After food' };
const RX_LEVOTHYROXINE: RxSeed = { medicineId: 'med-400', name: 'Levothyroxine', strength: '50 mcg', dosage: '1 tab', frequency: 'OD', route: 'PO', days: 30, instructions: 'Empty stomach, morning' };
const RX_SALBUTAMOL_INH: RxSeed = { medicineId: 'med-500', name: 'Salbutamol inhaler', strength: '100 mcg', dosage: '2 puffs', frequency: 'SOS', route: 'INH', days: 30, instructions: 'When breathless' };
const RX_BUDESONIDE_INH: RxSeed = { medicineId: 'med-501', name: 'Budesonide inhaler', strength: '200 mcg', dosage: '2 puffs', frequency: 'BD', route: 'INH', days: 30, instructions: 'Morning and night' };
const RX_CALCIUM:     RxSeed = { medicineId: 'med-600', name: 'Calcium + Vit D3', strength: '500 mg/250 IU', dosage: '1 tab', frequency: 'OD', route: 'PO', days: 30, instructions: 'After lunch' };
const RX_DICLOFENAC_GEL: RxSeed = { medicineId: 'med-700', name: 'Diclofenac gel', strength: '1%', dosage: 'Apply locally', frequency: 'BD', route: 'TOP', days: 7, instructions: 'Massage gently' };
const RX_CETIRIZINE:  RxSeed = { medicineId: 'med-800', name: 'Cetirizine',  strength: '10 mg',  dosage: '1 tab', frequency: 'OD', route: 'PO', days: 5, instructions: 'At bedtime' };
const RX_AZITHROMYCIN: RxSeed = { medicineId: 'med-810', name: 'Azithromycin', strength: '500 mg', dosage: '1 tab', frequency: 'OD', route: 'PO', days: 3, instructions: 'After food' };
const RX_FOLIC_ACID:  RxSeed = { medicineId: 'med-900', name: 'Folic acid',  strength: '5 mg',   dosage: '1 tab', frequency: 'OD', route: 'PO', days: 30, instructions: 'After breakfast' };
const RX_IRON:        RxSeed = { medicineId: 'med-901', name: 'Iron + Folic acid', strength: '60 mg', dosage: '1 tab', frequency: 'OD', route: 'PO', days: 30, instructions: 'After lunch' };
const RX_AMOXICILLIN_CHILD: RxSeed = { medicineId: 'med-820', name: 'Amoxicillin syrup', strength: '125 mg/5 ml', dosage: '5 ml', frequency: 'TDS', route: 'PO', days: 5, instructions: 'After food' };

/* --- Lab + radiology seeds --- */

const LAB_HBA1C_HIGH:  LabSeed = { testCode: 'HBA1C', testName: 'HbA1c',                  resultSummary: 'HbA1c 7.8% (ref < 6.5)',           flag: 'high' };
const LAB_LIPID_HIGH:  LabSeed = { testCode: 'LIPID', testName: 'Lipid Profile',          resultSummary: 'LDL 156 mg/dL â€” borderline-high',  flag: 'high' };
const LAB_LIPID_NORMAL: LabSeed = { testCode: 'LIPID', testName: 'Lipid Profile',          resultSummary: 'LDL 102 mg/dL â€” within target',   flag: 'normal' };
const LAB_TSH_HIGH:    LabSeed = { testCode: 'TSH',   testName: 'TSH',                    resultSummary: 'TSH 6.2 mIU/L (ref 0.4-4.0)',      flag: 'high' };
const LAB_TSH_NORMAL:  LabSeed = { testCode: 'TSH',   testName: 'TSH',                    resultSummary: 'TSH 2.4 mIU/L â€” euthyroid',       flag: 'normal' };
const LAB_RFT_HIGH:    LabSeed = { testCode: 'RFT',   testName: 'Renal Function Test',    resultSummary: 'Creatinine 1.4, eGFR 52 mL/min',   flag: 'high' };
const LAB_CBC_NORMAL:  LabSeed = { testCode: 'CBC',   testName: 'Complete Blood Count',   resultSummary: 'Hb 14.1, WBC 7.4, Plt 230',         flag: 'normal' };
const LAB_CBC_ABN:     LabSeed = { testCode: 'CBC',   testName: 'Complete Blood Count',   resultSummary: 'WBC 12.6 â€” mild leukocytosis',     flag: 'high' };
const LAB_LFT_NORMAL:  LabSeed = { testCode: 'LFT',   testName: 'Liver Function Test',    resultSummary: 'ALT 28, AST 30 â€” normal',           flag: 'normal' };
const LAB_URINE_NORMAL: LabSeed = { testCode: 'URINE', testName: 'Urine Routine',          resultSummary: 'No protein, no glucose, no RBC',  flag: 'normal' };

const RAD_XR_LSPINE:   RadSeed = { testCode: 'XR-LSP', testName: 'X-Ray L-Spine AP/Lat', modality: 'xray', resultSummary: 'Mild loss of lumbar lordosis. Disc spaces preserved. No fracture.' };
const RAD_XR_KNEE:     RadSeed = { testCode: 'XR-KNE', testName: 'X-Ray Knee AP/Lat',    modality: 'xray', resultSummary: 'Grade II osteoarthritis. Joint space narrowing.' };
const RAD_XR_SHOULDER: RadSeed = { testCode: 'XR-SHO', testName: 'X-Ray Shoulder AP',    modality: 'xray', resultSummary: 'No fracture. Acromiohumeral interval preserved.' };
const RAD_XR_HIP:      RadSeed = { testCode: 'XR-HIP', testName: 'X-Ray Hip AP',         modality: 'xray', resultSummary: 'No fracture. Decreased bone density noted.' };
const RAD_XR_CHEST:    RadSeed = { testCode: 'XR-CHE', testName: 'X-Ray Chest PA',       modality: 'xray', resultSummary: 'Cardiothoracic ratio normal. Lung fields clear.' };
const RAD_USG_ABD:     RadSeed = { testCode: 'USG-ABD', testName: 'USG Abdomen + Pelvis', modality: 'ultrasound',  resultSummary: 'Liver normal. No focal lesion. Both kidneys normal sized.' };
const RAD_USG_OBS:     RadSeed = { testCode: 'USG-OBS', testName: 'USG Obstetric',       modality: 'ultrasound',  resultSummary: 'Single live intrauterine gestation. Foetal growth appropriate for dates.' };

/* --- Templates --- */

const TPL = {
  hypertension_review: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'BP review + Rx refill',
      historyOfPresentIllness: 'Known hypertensive on Telmisartan. No headache or chest pain. Compliant with medication.',
      examinationFindings: 'BP 138/86 mmHg. Pulse 78/min regular. Heart sounds normal.',
      clinicalImpression: 'Hypertension â€” adequately controlled.',
      advice: 'Continue current regime. DASH diet, daily walk 30 min.',
    },
    diagnoses: [{ icd10: 'I10', description: 'Essential hypertension', type: 'primary' }],
    prescriptions: [RX_TELMISARTAN, RX_AMLODIPINE],
    labs: [],
    radiology: [],
  }),

  hypertension_with_lipid: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'BP review + lipid follow-up',
      historyOfPresentIllness: 'On HTN therapy. Concerned about cholesterol.',
      examinationFindings: 'BP 134/82 mmHg. Pulse 76/min. BMI 27.',
      clinicalImpression: 'Hypertension controlled. LDL borderline â€” start statin.',
      advice: 'Continue antihypertensives. Started statin. Recheck lipids in 12 weeks.',
    },
    diagnoses: [
      { icd10: 'I10', description: 'Essential hypertension', type: 'primary' },
      { icd10: 'E78.5', description: 'Hyperlipidemia, unspecified', type: 'secondary' },
    ],
    prescriptions: [RX_TELMISARTAN, RX_AMLODIPINE, RX_ATORVASTATIN],
    labs: [LAB_LIPID_HIGH],
    radiology: [],
  }),

  diabetes_review_hba1c: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'T2DM follow-up + HbA1c',
      historyOfPresentIllness: 'Diabetic for several years. Mixed compliance, occasional polyuria.',
      examinationFindings: 'BP 130/82 mmHg. Pulse 80/min. Feet: no ulcers, sensation intact.',
      clinicalImpression: 'Type 2 diabetes â€” sub-optimal control.',
      advice: 'Step up Metformin to 1g BD. Diet review. HbA1c in 12 weeks.',
    },
    diagnoses: [{ icd10: 'E11.9', description: 'Type 2 diabetes mellitus', type: 'primary' }],
    prescriptions: [RX_METFORMIN, RX_GLIMEPIRIDE],
    labs: [LAB_HBA1C_HIGH],
    radiology: [],
  }),

  diabetes_review: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Diabetes review',
      historyOfPresentIllness: 'Stable on oral agents. No hypoglycaemic episodes.',
      examinationFindings: 'BP 128/78 mmHg. Vitals stable. Feet examined â€” intact.',
      clinicalImpression: 'Type 2 diabetes â€” controlled.',
      advice: 'Continue current regime. Re-check HbA1c next quarter.',
    },
    diagnoses: [{ icd10: 'E11.9', description: 'Type 2 diabetes mellitus', type: 'primary' }],
    prescriptions: [RX_METFORMIN],
    labs: [],
    radiology: [],
  }),

  cad_review: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Cardiac follow-up',
      historyOfPresentIllness: 'Known CAD on dual antiplatelet + statin. No fresh chest pain.',
      examinationFindings: 'BP 132/82. Pulse 72. Heart sounds normal. No pedal oedema.',
      clinicalImpression: 'CAD â€” clinically stable on optimal medical therapy.',
      advice: 'Continue current Rx. ECG annually. Lipid in 6 months.',
    },
    diagnoses: [{ icd10: 'I25.10', description: 'CAD â€” stable', type: 'primary' }],
    prescriptions: [RX_ASPIRIN, RX_ATORVASTATIN, RX_TELMISARTAN],
    labs: [],
    radiology: [],
  }),

  cad_with_xray: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Cardiac review + Chest X-Ray',
      historyOfPresentIllness: 'Mild exertional dyspnoea past week.',
      examinationFindings: 'BP 138/86. Lungs: bibasal fine crepitations. JVP normal.',
      clinicalImpression: 'CAD â€” stable. CXR done to rule out failure.',
      advice: 'Continue Rx. Repeat ECG. Salt restriction reinforced.',
    },
    diagnoses: [{ icd10: 'I25.10', description: 'CAD â€” stable', type: 'primary' }],
    prescriptions: [RX_ASPIRIN, RX_ATORVASTATIN, RX_TELMISARTAN, RX_AMLODIPINE],
    labs: [],
    radiology: [RAD_XR_CHEST],
  }),

  ckd_kft_review: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'KFT review',
      historyOfPresentIllness: 'Known CKD. No oedema or oliguria.',
      examinationFindings: 'BP 138/84. No pedal oedema. Bladder not palpable.',
      clinicalImpression: 'CKD Stage 3a â€” stable.',
      advice: 'Renal-safe analgesia only. Avoid NSAIDs. KFT in 3 months.',
    },
    diagnoses: [{ icd10: 'N18.30', description: 'Chronic kidney disease, stage 3a', type: 'primary' }],
    prescriptions: [RX_TELMISARTAN, RX_AMLODIPINE],
    labs: [LAB_RFT_HIGH],
    radiology: [],
  }),

  thyroid_review: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'TSH review',
      historyOfPresentIllness: 'On Levothyroxine. No fresh symptoms of hypo/hyperthyroidism.',
      examinationFindings: 'Thyroid not enlarged. Pulse 76/min.',
      clinicalImpression: 'Hypothyroidism â€” controlled.',
      advice: 'Continue Levothyroxine. TSH every 6 months.',
    },
    diagnoses: [{ icd10: 'E03.9', description: 'Hypothyroidism, unspecified', type: 'primary' }],
    prescriptions: [RX_LEVOTHYROXINE],
    labs: [LAB_TSH_NORMAL],
    radiology: [],
  }),

  thyroid_uncontrolled: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'TSH check â€” fatigue ++',
      historyOfPresentIllness: 'Increasing tiredness, weight gain. On Levothyroxine 50 mcg.',
      examinationFindings: 'Pulse 64/min. Dry skin. No pedal oedema.',
      clinicalImpression: 'Hypothyroidism â€” sub-optimal. Step up dose.',
      advice: 'Increase Levothyroxine to 75 mcg. Recheck TSH in 8 weeks.',
    },
    diagnoses: [{ icd10: 'E03.9', description: 'Hypothyroidism', type: 'primary' }],
    prescriptions: [{ ...RX_LEVOTHYROXINE, strength: '75 mcg' }],
    labs: [LAB_TSH_HIGH],
    radiology: [],
  }),

  copd_review: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'COPD follow-up',
      historyOfPresentIllness: 'Chronic cough. No acute exacerbation this month.',
      examinationFindings: 'RR 18. SpO2 95% RA. Bilateral wheeze on auscultation.',
      clinicalImpression: 'COPD â€” stable.',
      advice: 'Continue inhalers. Influenza vaccine annually. Smoking cessation reinforced.',
    },
    diagnoses: [{ icd10: 'J44.9', description: 'COPD', type: 'primary' }],
    prescriptions: [RX_SALBUTAMOL_INH, RX_BUDESONIDE_INH],
    labs: [],
    radiology: [],
  }),

  copd_exacerbation: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Cough + breathlessness Ã— 4 days',
      historyOfPresentIllness: 'Known COPD. Productive cough, mild breathlessness. No fever.',
      examinationFindings: 'RR 22. SpO2 93%. Diffuse wheeze bilaterally.',
      clinicalImpression: 'COPD â€” mild exacerbation.',
      advice: 'Add antibiotic + oral steroid short course. Review in 5 days.',
    },
    diagnoses: [{ icd10: 'J44.1', description: 'COPD with acute exacerbation', type: 'primary' }],
    prescriptions: [RX_AZITHROMYCIN, RX_SALBUTAMOL_INH, RX_BUDESONIDE_INH],
    labs: [LAB_CBC_ABN],
    radiology: [RAD_XR_CHEST],
  }),

  asthma_review: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Asthma review',
      historyOfPresentIllness: 'Episodic wheeze, well-controlled on ICS. No nocturnal symptoms.',
      examinationFindings: 'Chest clear. SpO2 98%. PEFR ~ 80% predicted.',
      clinicalImpression: 'Bronchial asthma â€” controlled.',
      advice: 'Continue maintenance inhaler. SOS Salbutamol. Avoid triggers.',
    },
    diagnoses: [{ icd10: 'J45.9', description: 'Bronchial asthma', type: 'primary' }],
    prescriptions: [RX_BUDESONIDE_INH, RX_SALBUTAMOL_INH],
    labs: [],
    radiology: [],
  }),

  osteoporosis_review: (): EncounterTemplate => ({
    doctor: DR_NAVEEN,
    notes: {
      chiefComplaint: 'Hip/back stiffness â€” review',
      historyOfPresentIllness: 'Post-menopausal female. Generalised aches. No fresh falls.',
      examinationFindings: 'Mild kyphosis. Tenderness over lumbar spine. No focal neuro deficit.',
      clinicalImpression: 'Osteoporosis â€” fall-prevention emphasis.',
      advice: 'Calcium + Vit D continued. Weight-bearing exercises. Fall-proofing at home.',
    },
    diagnoses: [{ icd10: 'M81.0', description: 'Postmenopausal osteoporosis', type: 'primary' }],
    prescriptions: [RX_CALCIUM, RX_PARACETAMOL],
    labs: [],
    radiology: [RAD_XR_HIP],
  }),

  ortho_lbp_xray: (): EncounterTemplate => ({
    doctor: DR_NAVEEN,
    notes: {
      chiefComplaint: 'Lower back pain Ã— 2 weeks',
      historyOfPresentIllness: 'Onset insidious. Worse on prolonged sitting. No radiation, no bladder/bowel involvement.',
      examinationFindings: 'Lumbar paraspinal tenderness L4-L5. SLR negative bilaterally.',
      clinicalImpression: 'Mechanical low back pain.',
      advice: 'Activity modification. Hot fomentation. Lumbar core strengthening.',
    },
    diagnoses: [{ icd10: 'M54.5', description: 'Mechanical low back pain', type: 'primary' }],
    prescriptions: [RX_PARACETAMOL, RX_DICLOFENAC_GEL, RX_PANTOPRAZOLE],
    labs: [],
    radiology: [RAD_XR_LSPINE],
  }),

  ortho_lbp_followup: (): EncounterTemplate => ({
    doctor: DR_NAVEEN,
    notes: {
      chiefComplaint: 'LBP â€” review',
      historyOfPresentIllness: 'Pain settling. Continuing exercises.',
      examinationFindings: 'Reduced paraspinal tenderness. ROM improving.',
      clinicalImpression: 'Mechanical LBP â€” improving.',
      advice: 'Continue core exercises. SOS analgesia.',
    },
    diagnoses: [{ icd10: 'M54.5', description: 'Mechanical LBP â€” resolving', type: 'primary' }],
    prescriptions: [RX_PARACETAMOL],
    labs: [],
    radiology: [],
  }),

  ortho_knee_oa: (): EncounterTemplate => ({
    doctor: DR_NAVEEN,
    notes: {
      chiefComplaint: 'Bilateral knee pain',
      historyOfPresentIllness: 'Pain on stairs, morning stiffness < 30 min.',
      examinationFindings: 'Bilateral knee crepitus. Mild effusion right knee.',
      clinicalImpression: 'Bilateral knee osteoarthritis.',
      advice: 'Weight reduction. Quadriceps strengthening. Knee cap support.',
    },
    diagnoses: [{ icd10: 'M17.0', description: 'Bilateral primary osteoarthritis of knee', type: 'primary' }],
    prescriptions: [RX_PARACETAMOL, RX_DICLOFENAC_GEL],
    labs: [],
    radiology: [RAD_XR_KNEE],
  }),

  ortho_shoulder: (): EncounterTemplate => ({
    doctor: DR_NAVEEN,
    notes: {
      chiefComplaint: 'Right shoulder stiffness Ã— 2 months',
      historyOfPresentIllness: 'Painful overhead movement. No trauma.',
      examinationFindings: 'Reduced abduction 90Â°, external rotation limited.',
      clinicalImpression: 'Adhesive capsulitis â€” right shoulder.',
      advice: 'Capsular stretching. Physiotherapy referral. Re-assess in 6 weeks.',
    },
    diagnoses: [{ icd10: 'M75.0', description: 'Adhesive capsulitis of shoulder', type: 'primary' }],
    prescriptions: [RX_IBUPROFEN, RX_PANTOPRAZOLE],
    labs: [],
    radiology: [RAD_XR_SHOULDER],
  }),

  ortho_sprain: (): EncounterTemplate => ({
    doctor: DR_NAVEEN,
    notes: {
      chiefComplaint: 'Ankle pain after fall',
      historyOfPresentIllness: 'Twisted ankle while running. Swelling immediate.',
      examinationFindings: 'Lateral malleolar tenderness. Mild swelling. ROM painful.',
      clinicalImpression: 'Grade I lateral ankle sprain. No fracture suspected.',
      advice: 'RICE protocol. Crepe bandage. Weight-bear as tolerated.',
    },
    diagnoses: [{ icd10: 'S93.4', description: 'Lateral ankle ligament sprain', type: 'primary' }],
    prescriptions: [RX_PARACETAMOL, RX_DICLOFENAC_GEL],
    labs: [],
    radiology: [],
  }),

  viral_fever: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Fever Ã— 3 days, body ache',
      historyOfPresentIllness: 'High-grade intermittent fever with myalgia and headache. No rash, no bleeding.',
      examinationFindings: 'Temp 100.8Â°F. Throat mildly congested. No lymphadenopathy. Chest clear.',
      clinicalImpression: 'Viral fever â€” self-limiting.',
      advice: 'Hydration, rest, symptomatic. Review if fever > 5 days or rash appears.',
    },
    diagnoses: [{ icd10: 'B34.9', description: 'Viral infection, unspecified', type: 'provisional' }],
    prescriptions: [RX_PARACETAMOL],
    labs: [LAB_CBC_NORMAL],
    radiology: [],
  }),

  uri: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Cold, cough Ã— 5 days',
      historyOfPresentIllness: 'Runny nose, sore throat, dry cough. No fever today.',
      examinationFindings: 'Pharynx mildly congested. Chest clear. No fever.',
      clinicalImpression: 'Upper respiratory tract infection â€” viral.',
      advice: 'Steam inhalation. Adequate fluids. SOS antipyretics.',
    },
    diagnoses: [{ icd10: 'J06.9', description: 'URI, unspecified', type: 'primary' }],
    prescriptions: [RX_PARACETAMOL, RX_CETIRIZINE],
    labs: [],
    radiology: [],
  }),

  annual_checkup: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Annual health check-up',
      historyOfPresentIllness: 'No specific complaints. Routine review.',
      examinationFindings: 'Vitals within normal range. Systemic examination unremarkable.',
      clinicalImpression: 'Healthy adult â€” routine screening completed.',
      advice: 'Lifestyle measures. Re-check in 12 months.',
    },
    diagnoses: [{ icd10: 'Z00.0', description: 'General medical examination', type: 'primary' }],
    prescriptions: [],
    labs: [LAB_CBC_NORMAL, LAB_LIPID_NORMAL, LAB_LFT_NORMAL],
    radiology: [],
  }),

  antenatal_check: (): EncounterTemplate => ({
    doctor: DR_LAKSHMI,
    notes: {
      chiefComplaint: 'Antenatal check',
      historyOfPresentIllness: 'Current pregnancy progressing well. No bleeding, foetal movements adequate.',
      examinationFindings: 'BP 116/72. Fundal height appropriate. FHS heard.',
      clinicalImpression: 'Pregnancy â€” routine antenatal care.',
      advice: 'Continue iron + folic acid. Antenatal exercises. Next visit in 4 weeks.',
    },
    diagnoses: [{ icd10: 'Z34.9', description: 'Supervision of normal pregnancy', type: 'primary' }],
    prescriptions: [RX_FOLIC_ACID, RX_IRON, RX_CALCIUM],
    labs: [LAB_CBC_NORMAL, LAB_URINE_NORMAL],
    radiology: [RAD_USG_OBS],
  }),

  cycle_review: (): EncounterTemplate => ({
    doctor: DR_LAKSHMI,
    notes: {
      chiefComplaint: 'Cycle irregularity',
      historyOfPresentIllness: 'Cycles 35-50 days. No inter-menstrual bleeding.',
      examinationFindings: 'BMI 28. P/A soft, non-tender.',
      clinicalImpression: 'Irregular cycles â€” likely hypothyroid-related.',
      advice: 'Continue thyroid Rx. Diet + exercise advice. Follow up in 3 months.',
    },
    diagnoses: [{ icd10: 'N92.6', description: 'Irregular menstruation', type: 'primary' }],
    prescriptions: [RX_LEVOTHYROXINE],
    labs: [LAB_TSH_HIGH],
    radiology: [RAD_USG_ABD],
  }),

  paed_fever: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Fever Ã— 2 days, decreased intake',
      historyOfPresentIllness: 'Moderate-grade fever, no rash, no vomiting.',
      examinationFindings: 'Temp 101.2Â°F. Throat mildly congested. Chest clear. Active child.',
      clinicalImpression: 'Acute viral fever.',
      advice: 'Hydration. Sponging if fever > 102Â°F. Review in 48h.',
    },
    diagnoses: [{ icd10: 'B34.9', description: 'Viral infection, unspecified', type: 'provisional' }],
    prescriptions: [RX_PARACETAMOL],
    labs: [],
    radiology: [],
  }),

  paed_otitis: (): EncounterTemplate => ({
    doctor: DR_ANAND,
    notes: {
      chiefComplaint: 'Ear pain Ã— 1 day, fever',
      historyOfPresentIllness: 'Restless overnight. Crying on swallowing. Some hearing reduction.',
      examinationFindings: 'Right TM red, bulging. No discharge. Throat normal.',
      clinicalImpression: 'Acute otitis media â€” right ear.',
      advice: 'Antibiotic course + analgesia. Follow-up in 7 days.',
    },
    diagnoses: [{ icd10: 'H66.0', description: 'Acute suppurative otitis media', type: 'primary' }],
    prescriptions: [RX_AMOXICILLIN_CHILD, RX_PARACETAMOL],
    labs: [],
    radiology: [],
  }),

  dental_cleaning: (): EncounterTemplate => ({
    doctor: DR_MEERA,
    notes: {
      chiefComplaint: 'Dental cleaning + check',
      historyOfPresentIllness: 'Routine 6-month check. No specific pain.',
      examinationFindings: 'Generalised mild gingivitis. No carious lesions detected.',
      clinicalImpression: 'Gingivitis â€” routine prophylaxis.',
      advice: 'Twice-daily brushing. Floss daily. Re-check in 6 months.',
    },
    diagnoses: [{ icd10: 'K05.10', description: 'Chronic gingivitis', type: 'primary' }],
    prescriptions: [],
    labs: [],
    radiology: [],
  }),

  dental_filling: (): EncounterTemplate => ({
    doctor: DR_MEERA,
    notes: {
      chiefComplaint: 'Cold sensitivity â€” lower right molar',
      historyOfPresentIllness: 'Sharp pain on cold drinks last 2 weeks.',
      examinationFindings: 'Class I cavity in 46. No periapical involvement.',
      clinicalImpression: 'Dental caries â€” 46.',
      advice: 'Composite filling done. Avoid hard food Ã— 24h.',
    },
    diagnoses: [{ icd10: 'K02.9', description: 'Dental caries', type: 'primary' }],
    prescriptions: [RX_IBUPROFEN],
    labs: [],
    radiology: [],
  }),

  physio_knee: (): EncounterTemplate => ({
    doctor: DR_RAVI,
    notes: {
      chiefComplaint: 'Knee rehab â€” session',
      historyOfPresentIllness: 'Following OA management.',
      examinationFindings: 'Improving ROM. Quadriceps strength 4/5.',
      clinicalImpression: 'Knee OA â€” progressing rehab.',
      advice: 'Continue home exercises. Next session in 1 week.',
    },
    diagnoses: [{ icd10: 'M17.0', description: 'Knee OA â€” rehab', type: 'primary' }],
    prescriptions: [],
    labs: [],
    radiology: [],
  }),

  physio_lumbar: (): EncounterTemplate => ({
    doctor: DR_RAVI,
    notes: {
      chiefComplaint: 'Lumbar mobilisation',
      historyOfPresentIllness: 'Chronic LBP, post-acute phase.',
      examinationFindings: 'Reduced lumbar paraspinal tone. ROM improving.',
      clinicalImpression: 'Mechanical LBP â€” rehab.',
      advice: 'Continue isometric exercises. Next session in 1 week.',
    },
    diagnoses: [{ icd10: 'M54.5', description: 'Mechanical LBP â€” rehab', type: 'primary' }],
    prescriptions: [],
    labs: [],
    radiology: [],
  }),
} as const;

type TemplateKey = keyof typeof TPL;

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 *  Patient profiles â€” drives which templates and how many visits each patient gets
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */

interface PatientProfile {
  uhid: string;
  /** Months covered going back from 2026-05-15 â€” chronic patients have ~12 mo histories. */
  monthsCovered: number;
  /** Approx visits over the period. */
  visitCount: number;
  /** Template sequence the generator cycles through, oldest â†’ newest. */
  templates: TemplateKey[];
}

const PROFILES: PatientProfile[] = [
  /* Karthik â€” HTN + recurrent LBP */
  { uhid: 'KH-2026-00045', monthsCovered: 12, visitCount: 12, templates: [
    'ortho_shoulder', 'viral_fever', 'annual_checkup', 'hypertension_review', 'hypertension_with_lipid',
    'ortho_lbp_xray', 'hypertension_review', 'uri', 'hypertension_review', 'ortho_lbp_followup',
    'hypertension_review', 'hypertension_with_lipid',
  ]},
  /* Geetha â€” Hypothyroid + OBG */
  { uhid: 'KH-2024-08812', monthsCovered: 10, visitCount: 8, templates: [
    'thyroid_review', 'thyroid_uncontrolled', 'cycle_review', 'thyroid_review',
    'annual_checkup', 'thyroid_review', 'cycle_review', 'thyroid_review',
  ]},
  /* Aarav R (11) â€” healthy paediatric */
  { uhid: 'KH-2025-11203', monthsCovered: 12, visitCount: 4, templates: [
    'paed_otitis', 'paed_fever', 'paed_fever', 'uri',
  ]},
  /* Sundar (71) â€” multi-comorbid, monthly */
  { uhid: 'KH-2018-00094', monthsCovered: 12, visitCount: 13, templates: [
    'cad_review', 'diabetes_review_hba1c', 'hypertension_review', 'cad_review', 'cad_with_xray',
    'ckd_kft_review', 'hypertension_review', 'diabetes_review_hba1c', 'annual_checkup',
    'cad_review', 'diabetes_review', 'hypertension_review', 'diabetes_review_hba1c',
  ]},
  /* Meera S. (58f) â€” DM + OA, monthly */
  { uhid: 'KH-2026-00046', monthsCovered: 11, visitCount: 11, templates: [
    'diabetes_review', 'ortho_knee_oa', 'diabetes_review_hba1c', 'physio_knee',
    'diabetes_review_hba1c', 'ortho_knee_oa', 'diabetes_review', 'physio_knee',
    'diabetes_review', 'diabetes_review_hba1c', 'ortho_knee_oa',
  ]},
  /* Rajan S. (62) â€” HTN + CKD */
  { uhid: 'KH-2023-04501', monthsCovered: 10, visitCount: 9, templates: [
    'ckd_kft_review', 'hypertension_review', 'ckd_kft_review', 'hypertension_review',
    'ckd_kft_review', 'annual_checkup', 'hypertension_review', 'ckd_kft_review', 'hypertension_review',
  ]},
  /* Anjali S. (26) â€” young healthy */
  { uhid: 'KH-2025-09812', monthsCovered: 12, visitCount: 3, templates: [
    'viral_fever', 'uri', 'annual_checkup',
  ]},
  /* Ramesh B. (67) â€” CAD + HTN, monthly */
  { uhid: 'KH-2026-00047', monthsCovered: 11, visitCount: 10, templates: [
    'hypertension_review', 'cad_review', 'cad_with_xray', 'hypertension_review', 'cad_review',
    'annual_checkup', 'cad_review', 'hypertension_review', 'cad_review', 'hypertension_review',
  ]},
  /* Sundari B. (64) â€” T2DM */
  { uhid: 'KH-2024-06210', monthsCovered: 11, visitCount: 8, templates: [
    'diabetes_review', 'diabetes_review_hba1c', 'diabetes_review', 'diabetes_review',
    'diabetes_review_hba1c', 'annual_checkup', 'diabetes_review', 'diabetes_review_hba1c',
  ]},
  /* Aarav S (9) â€” paed */
  { uhid: 'KH-2026-00048', monthsCovered: 12, visitCount: 4, templates: [
    'paed_fever', 'paed_otitis', 'uri', 'paed_fever',
  ]},
  /* Vivek K. (41) â€” healthy */
  { uhid: 'KH-2024-03301', monthsCovered: 12, visitCount: 4, templates: [
    'viral_fever', 'annual_checkup', 'uri', 'dental_cleaning',
  ]},
  /* Priya K. (38, asthma) */
  { uhid: 'KH-2024-03302', monthsCovered: 12, visitCount: 6, templates: [
    'asthma_review', 'uri', 'asthma_review', 'asthma_review', 'viral_fever', 'asthma_review',
  ]},
  /* Imran Khan (35) */
  { uhid: 'KH-2025-08801', monthsCovered: 12, visitCount: 4, templates: [
    'annual_checkup', 'uri', 'dental_cleaning', 'viral_fever',
  ]},
  /* Sameera Khan (30) */
  { uhid: 'KH-2025-08802', monthsCovered: 12, visitCount: 4, templates: [
    'cycle_review', 'annual_checkup', 'cycle_review', 'antenatal_check',
  ]},
  /* Lakshmi N. (71) â€” Osteoporosis + HTN */
  { uhid: 'KH-2026-00049', monthsCovered: 11, visitCount: 10, templates: [
    'osteoporosis_review', 'hypertension_review', 'osteoporosis_review', 'hypertension_review',
    'physio_lumbar', 'osteoporosis_review', 'hypertension_review', 'osteoporosis_review',
    'hypertension_review', 'osteoporosis_review',
  ]},
  /* Naren K. (76) â€” multi-comorbid */
  { uhid: 'KH-2020-00721', monthsCovered: 11, visitCount: 11, templates: [
    'cad_review', 'hypertension_review', 'diabetes_review_hba1c', 'cad_with_xray',
    'hypertension_review', 'annual_checkup', 'cad_review', 'diabetes_review',
    'cad_review', 'hypertension_review', 'diabetes_review_hba1c',
  ]},
  /* Suresh B. (49) â€” HTN */
  { uhid: 'KH-2026-00050', monthsCovered: 11, visitCount: 7, templates: [
    'hypertension_review', 'annual_checkup', 'hypertension_review', 'hypertension_with_lipid',
    'uri', 'hypertension_review', 'hypertension_review',
  ]},
  /* Sunita (34) â€” healthy */
  { uhid: 'KH-2026-00051', monthsCovered: 12, visitCount: 3, templates: [
    'viral_fever', 'annual_checkup', 'uri',
  ]},
  /* Vikram (51) â€” HTN + Hyperlipidemia */
  { uhid: 'KH-2026-00052', monthsCovered: 11, visitCount: 9, templates: [
    'annual_checkup', 'hypertension_with_lipid', 'hypertension_review', 'hypertension_with_lipid',
    'hypertension_review', 'hypertension_with_lipid', 'hypertension_review', 'hypertension_review',
    'hypertension_with_lipid',
  ]},
  /* Aisha (28) â€” healthy + allergy */
  { uhid: 'KH-2026-00053', monthsCovered: 12, visitCount: 3, templates: [
    'uri', 'viral_fever', 'annual_checkup',
  ]},
  /* Ravi A. (45) â€” T2DM */
  { uhid: 'KH-2026-00054', monthsCovered: 11, visitCount: 8, templates: [
    'diabetes_review_hba1c', 'diabetes_review', 'diabetes_review_hba1c', 'annual_checkup',
    'diabetes_review', 'diabetes_review_hba1c', 'diabetes_review', 'diabetes_review_hba1c',
  ]},
  /* Divya (32) â€” healthy */
  { uhid: 'KH-2026-00055', monthsCovered: 12, visitCount: 3, templates: [
    'cycle_review', 'uri', 'annual_checkup',
  ]},
  /* Sanjay (60) â€” HTN + COPD */
  { uhid: 'KH-2026-00058', monthsCovered: 11, visitCount: 10, templates: [
    'copd_exacerbation', 'copd_review', 'hypertension_review', 'copd_review',
    'hypertension_review', 'annual_checkup', 'copd_review', 'hypertension_review',
    'copd_exacerbation', 'copd_review',
  ]},
  /* Latha Devi (67) â€” multi */
  { uhid: 'KH-2026-00061', monthsCovered: 11, visitCount: 10, templates: [
    'diabetes_review', 'ortho_knee_oa', 'hypertension_review', 'diabetes_review_hba1c',
    'physio_knee', 'hypertension_review', 'diabetes_review', 'ortho_knee_oa',
    'hypertension_review', 'diabetes_review_hba1c',
  ]},
  /* Manjunath (71) â€” multi */
  { uhid: 'KH-2026-00064', monthsCovered: 11, visitCount: 10, templates: [
    'ckd_kft_review', 'diabetes_review', 'cad_review', 'ckd_kft_review',
    'hypertension_review', 'annual_checkup', 'diabetes_review_hba1c', 'cad_review',
    'ckd_kft_review', 'diabetes_review_hba1c',
  ]},
  /* Kishore B. (78) â€” multi */
  { uhid: 'KH-2026-00068', monthsCovered: 11, visitCount: 11, templates: [
    'cad_review', 'hypertension_review', 'diabetes_review_hba1c', 'cad_with_xray',
    'hypertension_review', 'annual_checkup', 'cad_review', 'diabetes_review',
    'cad_review', 'hypertension_review', 'cad_review',
  ]},
  /* Anand M. (88) â€” multi (highest visits) */
  { uhid: 'KH-2024-04401', monthsCovered: 12, visitCount: 13, templates: [
    'hypertension_review', 'cad_review', 'ckd_kft_review', 'hypertension_review',
    'cad_review', 'ckd_kft_review', 'hypertension_review', 'annual_checkup',
    'cad_with_xray', 'cad_review', 'ckd_kft_review', 'hypertension_review', 'cad_review',
  ]},
  /* Tamilarasan (80) â€” multi */
  { uhid: 'KH-2024-04420', monthsCovered: 12, visitCount: 12, templates: [
    'cad_review', 'ckd_kft_review', 'hypertension_review', 'cad_review',
    'ckd_kft_review', 'hypertension_review', 'annual_checkup', 'cad_review',
    'ckd_kft_review', 'hypertension_review', 'cad_review', 'hypertension_review',
  ]},
  /* Yogesh (5) â€” paed */
  { uhid: 'KH-2024-04424', monthsCovered: 12, visitCount: 4, templates: [
    'paed_otitis', 'paed_fever', 'uri', 'paed_fever',
  ]},
  /* Zara (1) â€” paed */
  { uhid: 'KH-2024-04425', monthsCovered: 9, visitCount: 4, templates: [
    'paed_fever', 'paed_fever', 'paed_otitis', 'paed_fever',
  ]},
];

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 *  Generator â€” turns (profile Ã— template Ã— date) into ConsultationContext
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */

/** Reference "today" anchor used by the doctor app; visits are spaced backwards from here. */
const TODAY = new Date('2026-05-15T00:00:00Z').getTime();
const DAY = 24 * 60 * 60 * 1000;

/** Deterministic vitals â€” varies slightly per opNumber so each visit doesn't look identical. */
const vitalsFor = (patient: PatientSummary, opSeed: number): Vitals => {
  const isElderly = patient.ageYears >= 65;
  const sysBase = isElderly ? 138 : 124;
  const pulseBase = isElderly ? 78 : 74;
  const tempBase = 98.4;
  const wobble = (n: number, range: number): number => n + ((opSeed * 7) % (range * 2)) - range;
  return {
    recordedAt: new Date(TODAY - DAY * 365).toISOString(),
    recordedBy: 'Nurse Saritha',
    bpSystolic:  Math.round(wobble(sysBase, 8)),
    bpDiastolic: Math.round(wobble(82, 5)),
    pulseRate:   Math.round(wobble(pulseBase, 6)),
    temperatureF: Number((tempBase + ((opSeed * 13) % 30) / 100).toFixed(1)),
    spo2: 97 + (opSeed % 3),
    respiratoryRate: 16,
    weightKg: patient.ageYears <= 12 ? 25 + patient.ageYears : 65 + (opSeed % 18),
    heightCm: patient.ageYears <= 12 ? 80 + patient.ageYears * 6 : 165 + (opSeed % 12),
    bmi: 25 + (opSeed % 5),
    painScore: 1 + (opSeed % 6),
  };
};

const buildEncounter = (
  opNumber: string,
  patient: PatientSummary,
  template: EncounterTemplate,
  startedAt: Date,
  opSeed: number,
): ConsultationContext => {
  const lockedAt = new Date(startedAt.getTime() + 45 * 60 * 1000);
  const prescriptionItems: PrescriptionItem[] = template.prescriptions.map((rx, i) => ({
    id: `${opNumber}-pi-${i}`,
    medicineId: rx.medicineId,
    medicineNameSnapshot: rx.name,
    strength: rx.strength,
    dosage: rx.dosage,
    frequency: rx.frequency,
    route: rx.route,
    durationDays: rx.days,
    quantityPrescribed: rx.days * (rx.frequency === 'BD' ? 2 : rx.frequency === 'TDS' ? 3 : rx.frequency === 'QID' ? 4 : 1),
    dispensedQty: rx.days * (rx.frequency === 'BD' ? 2 : rx.frequency === 'TDS' ? 3 : rx.frequency === 'QID' ? 4 : 1),
    instructions: rx.instructions,
    severity: 'ok',
  }));
  const labOrders: LabOrder[] = template.labs.map((l, i) => ({
    id: `${opNumber}-lab-${i}`,
    orderedAt: new Date(startedAt.getTime() + 10 * 60 * 1000).toISOString(),
    status: 'reported',
    testCode: l.testCode,
    testName: l.testName,
    flag: l.flag,
    resultSummary: l.resultSummary,
    reportPdfUrl: PDF_LAB(opNumber, l.testCode),
  }));
  const radiologyOrders: RadiologyOrder[] = template.radiology.map((r, i) => ({
    id: `${opNumber}-rad-${i}`,
    orderedAt: new Date(startedAt.getTime() + 15 * 60 * 1000).toISOString(),
    status: 'reported',
    testCode: r.testCode,
    testName: r.testName,
    modality: r.modality,
    resultSummary: r.resultSummary,
    reportPdfUrl: PDF_RAD(opNumber, r.testCode),
  }));
  return {
    opNumber,
    status: status('consultation_done'),
    startedAt: startedAt.toISOString(),
    lockedAt: lockedAt.toISOString(),
    patient,
    latestVitals: vitalsFor(patient, opSeed),
    notes: template.notes,
    diagnoses: template.diagnoses.map((d, i) => ({ ...d, id: `${opNumber}-dx-${i}` })),
    prescriptionItems,
    labOrders,
    radiologyOrders,
    recommendations: [],
    criticalNotifications: [],
  };
};

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 *  Metadata + generation pass
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */

export interface PastEncounterMeta {
  opNumber: string;
  doctorId: string;
  doctorName: string;
  department: string;
  uhid: string;
  /** YYYY-MM-DD. */
  visitDate: string;
}

// Past visits are numbered well above the live-queue band (OP-2026-001xx)
// so they never collide with TODAY_QUEUE rows or `mockConsultation`'s
// OP-2026-00121 anchor.
let opSeq = 5000;
const nextOpNumber = (date: Date): string => {
  opSeq += 1;
  return `OP-${date.getUTCFullYear()}-${String(opSeq).padStart(5, '0')}`;
};

const generatedEncounters: Record<string, ConsultationContext> = {};
const generatedMeta: PastEncounterMeta[] = [];

for (const profile of PROFILES) {
  const patient = findPatient(profile.uhid);
  const spacingDays = Math.floor((profile.monthsCovered * 30) / profile.visitCount);
  for (let i = 0; i < profile.templates.length; i += 1) {
    const tplKey = profile.templates[i];
    const template = TPL[tplKey]();
    // Oldest visit first; the newest visit ends ~15 days ago (so the
    // visit history doesn't overlap with today's live queue).
    const daysAgo = (profile.templates.length - i) * spacingDays + 15;
    const visitTime = new Date(TODAY - daysAgo * DAY);
    const opNumber = nextOpNumber(visitTime);
    const ctx = buildEncounter(opNumber, patient, template, visitTime, opSeq);
    generatedEncounters[opNumber] = ctx;
    generatedMeta.push({
      opNumber,
      doctorId: template.doctor.id,
      doctorName: template.doctor.name,
      department: template.doctor.department,
      uhid: patient.uhid,
      visitDate: visitTime.toISOString().slice(0, 10),
    });
  }
}

/** All past encounters, keyed by opNumber â€” the single source of truth. */
export const mockPastEncounters: Record<string, ConsultationContext> = generatedEncounters;

/** Parallel metadata exported for encounterMocks to derive past-visit maps. */
export const mockPastEncounterMeta: PastEncounterMeta[] = generatedMeta;

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 *  Live demo consultation (Karthik) â€” anchor for the doctor walkthrough
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */

const sharedPatient = findPatient('KH-2026-00045');

export const mockConsultation: ConsultationContext = {
  opNumber: 'OP-2026-00121',
  status: status('in_consultation'),
  startedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  patient: sharedPatient,
  latestVitals: {
    recordedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    recordedBy: 'Nurse Saritha',
    bpSystolic: 138, bpDiastolic: 86, pulseRate: 82,
    temperatureF: 98.4, spo2: 98, respiratoryRate: 16,
    weightKg: 78, heightCm: 173, bmi: 26.1, painScore: 6,
  },
  notes: {
    chiefComplaint: 'Lower back pain Ã— 3 weeks, worse on bending',
    historyOfPresentIllness:
      'Insidious onset, dull aching pain, radiates to right buttock. No bladder/bowel involvement. No trauma. Worse on prolonged sitting.',
    examinationFindings:
      'Lumbar paraspinal tenderness L4-L5. SLR 60Â° right, negative left. No neurological deficit. Power 5/5 all groups.',
    clinicalImpression: 'Mechanical low back pain â€” likely myofascial. R/O early disc bulge.',
    advice: 'Activity modification. Postural correction. Lumbar isometrics.',
  },
  diagnoses: [
    { id: 'dx-1', icd10: 'M54.5', description: 'Low back pain', type: 'primary' },
  ],
  prescriptionItems: [],
  labOrders: [
    { id: 'lab-pending-1', orderedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),  status: 'in_progress', testCode: 'CBC',       testName: 'Complete Blood Count' },
    { id: 'lab-crit-1',    orderedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),  status: 'reported',    testCode: 'POTASSIUM', testName: 'Serum Potassium', flag: 'critical_high', resultSummary: 'K+ 6.4 mmol/L (ref 3.5â€“5.1) â€” critical hyperkalaemia. Repeat sample sent.' },
    { id: 'lab-abn-1',     orderedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(), status: 'reported',    testCode: 'CRP',       testName: 'C-Reactive Protein', flag: 'high',          resultSummary: 'CRP 48 mg/L (ref < 5) â€” elevated, consistent with active inflammation.' },
  ],
  radiologyOrders: [
    { id: 'rad-done-1', orderedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), status: 'reported', testCode: 'XR-LSP', testName: 'X-Ray L-Spine AP/Lat', modality: 'xray', resultSummary: 'Mild loss of lumbar lordosis. No fracture. Disc spaces preserved.' },
  ],
  recommendations: [],
  criticalNotifications: [
    {
      id: 'notif-crit-1',
      labOrderId: 'lab-crit-1',
      testCode: 'POTASSIUM',
      testName: 'Serum Potassium',
      flag: 'critical_high',
      resultSummary: 'K+ 6.4 mmol/L (ref 3.5â€“5.1) â€” critical hyperkalaemia.',
      occurredAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
      ackRequired: true,
    },
  ],
};

void mockDoctor;
void mockPatients;

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 *  Prescription templates (unchanged demo data)
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */

const samplePrescriptionItems = (): PrescriptionItem[] => [
  { id: 'pi-1', medicineId: 'med-100', medicineNameSnapshot: 'Paracetamol',  strength: '500 mg', dosage: '1 tab', frequency: 'TDS', route: 'PO', durationDays: 5, instructions: 'After food',     severity: 'ok' },
  { id: 'pi-2', medicineId: 'med-140', medicineNameSnapshot: 'Pantoprazole', strength: '40 mg',  dosage: '1 tab', frequency: 'OD',  route: 'PO', durationDays: 7, instructions: 'Before breakfast', severity: 'low' },
];

export const mockPrescriptionTemplates: PrescriptionTemplate[] = [
  { id: 'tpl-1', name: 'Acute mechanical LBP â€” short course', specialty: 'Orthopaedics',     itemCount: 3, updatedAt: '2026-03-12T10:30:00Z', items: samplePrescriptionItems() },
  { id: 'tpl-2', name: 'Post-op knee arthroscopy day-1',      specialty: 'Orthopaedics',     itemCount: 4, updatedAt: '2026-02-21T14:05:00Z', items: samplePrescriptionItems() },
  { id: 'tpl-3', name: 'OA Knee â€” symptomatic',                specialty: 'Orthopaedics',     itemCount: 3, updatedAt: '2025-12-30T08:55:00Z', items: samplePrescriptionItems() },
  { id: 'tpl-4', name: 'Hypertension â€” first-line combo',     specialty: 'General Medicine', itemCount: 3, updatedAt: '2026-01-10T08:00:00Z', items: samplePrescriptionItems() },
  { id: 'tpl-5', name: 'T2DM â€” Metformin + statin starter',   specialty: 'General Medicine', itemCount: 3, updatedAt: '2026-02-01T08:00:00Z', items: samplePrescriptionItems() },
];
