package com.hospital.management.opd.appointment;

import com.hospital.management.platform.audit.AuditableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.UuidGenerator;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * A bookable time slot for a doctor. Generated by the slot-creation service
 * based on doctor_profiles.available_days and doctor_leaves.
 * status: available | booked | blocked | cancelled
 */
@Entity
@Table(name = "appointment_slots")
@Getter
public class AppointmentSlot extends AuditableEntity {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /** FK → users(id) RESTRICT — must be a doctor-role user. */
    @Column(nullable = false, updatable = false)
    private UUID doctorId;

    @Column(nullable = false, updatable = false)
    private OffsetDateTime slotStart;

    @Column(nullable = false)
    private int durationMins;

    @Setter @Column(nullable = false)
    private String status;

    /** FK → users(id) SET NULL — who booked this slot (receptionist / patient via app). */
    @Setter @Column
    private UUID bookedBy;

    @Setter @Column
    private String blockedReason;

    protected AppointmentSlot() {}

    public AppointmentSlot(UUID doctorId, OffsetDateTime slotStart, int durationMins, UUID createdBy) {
        this.doctorId     = doctorId;
        this.slotStart    = slotStart;
        this.durationMins = durationMins;
        this.status       = "available";
        setCreatedBy(createdBy);
    }

    public void book(UUID bookedByUserId) {
        this.status   = "booked";
        this.bookedBy = bookedByUserId;
    }

    public void block(String reason, UUID actorId) {
        this.status        = "blocked";
        this.blockedReason = reason;
        setUpdatedBy(actorId);
    }

    public void cancel(UUID actorId) {
        this.status = "cancelled";
        setUpdatedBy(actorId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AppointmentSlot s)) return false;
        return Objects.equals(doctorId, s.doctorId) && Objects.equals(slotStart, s.slotStart);
    }

    @Override
    public int hashCode() { return Objects.hash(doctorId, slotStart); }
}
