package com.hospital.management.opd.appointment;

import com.hospital.management.platform.audit.AuditableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.UuidGenerator;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * A scheduled patient appointment. appointmentNo is generated by the app (e.g. APT-2026-00001).
 * status lifecycle: booked → confirmed → arrived → in_consultation → completed
 *                                                               ↘ cancelled | no_show
 * visit_type: new | follow_up | emergency | procedure
 * source: walk_in | phone | online | referral
 */
@Entity
@Table(name = "appointments")
@Getter
public class Appointment extends AuditableEntity {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(updatable = false, nullable = false)
    private UUID id;

    @Column(nullable = false, unique = true, updatable = false)
    private String appointmentNo;

    @Setter @Column(nullable = false)
    private UUID patientId;

    @Setter @Column(nullable = false)
    private UUID doctorId;

    /** FK → appointment_slots(id) RESTRICT. NULL for walk-in bookings without a pre-allocated slot. */
    @Setter @Column
    private UUID slotId;

    @Setter @Column(nullable = false)
    private OffsetDateTime scheduledAt;

    @Setter @Column(nullable = false)
    private String visitType;

    @Setter @Column(nullable = false)
    private String status;

    @Column(nullable = false, updatable = false)
    private String source;

    @Setter @Column
    private String reason;

    @Setter @Column
    private OffsetDateTime cancelledAt;

    @Setter @Column
    private UUID cancelledBy;

    @Setter @Column
    private String cancelReason;

    protected Appointment() {}

    public Appointment(String appointmentNo, UUID patientId, UUID doctorId,
                       OffsetDateTime scheduledAt, String visitType, String source,
                       UUID createdBy) {
        this.appointmentNo = appointmentNo;
        this.patientId     = patientId;
        this.doctorId      = doctorId;
        this.scheduledAt   = scheduledAt;
        this.visitType     = visitType;
        this.status        = "booked";
        this.source        = source;
        setCreatedBy(createdBy);
    }

    public void cancel(UUID actorId, String cancelReasonText) {
        this.status      = "cancelled";
        this.cancelledAt = OffsetDateTime.now();
        this.cancelledBy = actorId;
        this.cancelReason = cancelReasonText;
        setUpdatedBy(actorId);
    }

    public void markNoShow(UUID actorId) {
        this.status = "no_show";
        setUpdatedBy(actorId);
    }

    public boolean isCancellable() {
        return "booked".equals(status) || "confirmed".equals(status);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Appointment a)) return false;
        return appointmentNo != null && appointmentNo.equals(a.appointmentNo);
    }

    @Override
    public int hashCode() { return Objects.hash(appointmentNo); }

    @Override
    public String toString() {
        return "Appointment[no=" + appointmentNo + ", patient=" + patientId + ", status=" + status + "]";
    }
}
